#!/usr/bin/env sh
# Rogue Security - hook-log shipper (POSIX sh). Siblings: ship-logs.ps1 (native
# Windows) and plugins/gemini/scripts/ship-logs.mjs (Node).
#
# Uploads the un-shipped tail of this machine's Rogue hook log to
# /api/v1/hooks/logs, so a support engineer can read it WITHOUT an endpoint agent
# on the box. Design, rationale and the state-machine proof: docs/plugin-log-shipper.md.
#
#   sh ship-logs.sh <plugin-root> <shipper-slug> <shipper-version> <agent-family>
#
# NO ARGUMENTS -> collect EVERY known agent's log (ROGUE_SHIP_ALL is implied: with
# no slug there is no "own log" to pick), reporting shipper "unknown". That is the
# support invocation; /rogue:status prints it with the arguments filled in.
#
# EDIT scripts/shared/ship-logs.sh. THIS IS A COMMITTED, BYTE-IDENTICAL COPY of it,
# regenerated by scripts/sync-shared-scripts.sh and verified by
# tests/test_ship_logs.sh + `--check` in CI. An edit made here is silently reverted
# by the next sync.
#
# The copies exist because each plugin is distributed as a SELF-CONTAINED DIRECTORY:
# Cursor, Gemini and Antigravity are installed by copying just their own tree, so on
# a Cursor-only machine nothing outside ~/.cursor/plugins/local/rogue exists and a
# runtime `.`-source of a shared path would find nothing. They are COMMITTED rather
# than generated at release because `claude plugin install` / `codex plugin add` /
# `copilot plugin install` git-clone this monorepo and use plugins/<x>/ with no
# build step at all.
#
# Every per-plugin difference is an ARGUMENT, never a variable read from the
# environment - which is what lets the copies be byte-identical at all. The
# plugin-root var name is the one thing that genuinely differs between them
# (CLAUDE_PLUGIN_ROOT / PLUGIN_ROOT / CURSOR_PLUGIN_ROOT), and the caller already
# holds it. Never reference a plugin-specific env var here.
#
# <agent-family> is passed in and NEVER derived from the slug: the two are
# different vocabularies (codex's log slug is `codex` but its family is `openai`).
# A slug->family table inside a byte-identical script would be one more thing to
# keep in lockstep.
#
# NAMING: POSIX sh has NO LOCAL VARIABLES - every assignment inside a function is
# global. So each function's temporaries are prefixed with a tag for that function
# (`_chunk_*` in ship_next_chunk, `_drain_*` in drain_file, ...). This is not
# decoration: drain_file holds its own file and size while calling ship_next_chunk,
# and a shared bare name like `_file` would be clobbered by the callee and turn the
# drain loop into an infinite one. Add a temporary -> give it the caller's prefix.
# UPPER_CASE names are the deliberately shared state, set by the stages in main().
#
# Fail-open everywhere, `exit 0` on every path, and deliberately NO `set -e`:
#   * non-zero is NORMAL here - curl returns 7 with no network, grep returns 1 on
#     no match - and under `set -e` either would abort mid-run, skipping the state
#     write and the lock release.
#   * a non-zero exit means something to the caller (Copilot's preToolUse is
#     fail-CLOSED), so a broken shipper must be silence, never a failure.
set -u

# ── constants ──────────────────────────────────────────────────────────────
SHIP_ENDPOINT_PATH="/api/v1/hooks/logs"
KNOWN_LOG_SLUGS="claude codex cursor gemini copilot antigravity kiro"
# Bytes scanned when fingerprinting a log's first line. NOT the 200 an earlier
# draft of the design doc specified: a real log line is timestamp + provider +
# event + up to 400 chars of `raw=`, i.e. commonly 500-700 bytes, so a 200-byte
# window would find no newline in the first line of a typical log and the whole
# rotation check would silently never engage.
HEAD_WINDOW_BYTES=4096
# Windows of MAX_LINE_BYTES scanned when hunting the end of an over-long line:
# 256 MiB at the defaults. Past that the file is not a log any more, and the
# shipper stalls rather than advancing (see find_line_end / ship_oversize_line for
# why an advance that does not land after a newline is unsafe at any price).
MAX_SCAN_WINDOWS=64
LOCK_STALE_SECONDS=600
# The same bound in minutes, because the marker-less case ages the lock DIRECTORY
# with `find -mmin` and find has no seconds granularity. Integer division, so keep
# LOCK_STALE_SECONDS a whole number of minutes.
LOCK_STALE_MINUTES=$((LOCK_STALE_SECONDS / 60))
# Hard iteration guard on the chunk loop. MAX_RUN_BYTES/MAX_CHUNK_BYTES is 10 at
# the defaults; this only ever bites if a knob is set to something strange.
MAX_CHUNKS_PER_DRAIN=64
HTTP_TIMEOUT=15

# ── everything below is set by the stages in main() ────────────────────────
PLUGIN_ROOT=""
SHIPPER_SLUG="unknown"
SHIPPER_VERSION="unknown"
AGENT_FAMILY=""
SHIP_ALL_LOGS=0
EXACT_LOG_FILE=""      # non-empty when ROGUE_LOG_FILE pins one exact path
LOG_DIR=""
STATE_DIR=""
TMP_DIR=""
HELD_LOCK_DIR=""
SELF_LOG_FILE=""       # our own diagnostics; empty when the slug is unknown
API_KEY=""
SHIP_URL=""
HOST_NAME=""
ACTOR_EMAIL=""
ACTOR_NAME=""
MIN_INTERVAL_SECONDS=900
MAX_CHUNK_BYTES=1048576
MAX_RUN_BYTES=10485760
MAX_LINE_BYTES=4194304
# per-target working state
TARGET_BASENAME=""; TARGET_FAMILY=""; STATE_KEY=""
OFFSET=0; STATE_HEAD=""; STATE_SIZE=0; STATE_PATH=""
ADVANCE_BYTES=0; RUN_BYTES_SENT=0
LINE_LENGTH=0; LINE_SEARCH_HIT_EOF=0

debug() { [ -n "${ROGUE_DEBUG:-}" ] && printf '[rogue-ship] %s\n' "$*" >&2; return 0; }

# Our own diagnostics land in the SHIPPING plugin's log file, tagged
# `event=ShipLogs`, and ONLY for notable outcomes (a failure or a skip) - never
# on the happy path. Two reasons for that gate:
#   * a line per run would mean every run has new bytes to ship, which would
#     destroy the "an idle machine makes no HTTP request at all" property that
#     makes the 15-minute throttle cheap;
#   * it lands in the file that gets uploaded, so the failure it describes is
#     readable in the dataset once shipping recovers - a local-only shipper log
#     is invisible for exactly the failure it records.
# The shipper NEVER rotates that file even if its own line pushes it over the
# cap: renaming a log we may be part-way through reading is precisely the
# rotation-under-us hazard the head re-check exists to catch. Rotation is
# deferred to the dispatcher's next write, which is where phase 1 enforces it.
log() {
  # ALSO to stderr under ROGUE_DEBUG, and unconditionally - before the
  # SELF_LOG_FILE gate below. The no-argument support invocation has no slug, so it
  # has no log file of its own to write to, and every failure reason (`http=<code>`,
  # `reason=no-actor`) used to vanish on exactly the run a support engineer is told
  # to make. The file is where the outcome is durable; stderr is where it is
  # visible.
  debug "$*"
  [ -n "$SELF_LOG_FILE" ] || return 0
  ( umask 077
    mkdir -p "$(dirname "$SELF_LOG_FILE")" 2>/dev/null
    printf '%s provider=%s event=ShipLogs %s\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$SHIPPER_SLUG" "$*" >> "$SELF_LOG_FILE" 2>/dev/null )
  return 0
}

# Same escaping as every heartbeat's esc(). Deliberately NOT also stripping
# control characters: these values (host, actor, slug, version, basename) must be
# byte-identical to the ones the heartbeat sent, or the log_source row and the
# roster row key differently and the logs attach to nothing.
json_escape() { printf '%s' "${1:-}" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

trim() {
  _trim_value="${1:-}"
  _trim_value="${_trim_value#"${_trim_value%%[![:space:]]*}"}"
  _trim_value="${_trim_value%"${_trim_value##*[![:space:]]}"}"
  printf '%s' "$_trim_value"
}

# Lexical absolutisation ONLY - no symlink resolution. `path=` in the state file
# is compared as a STRING by all three implementations, and PowerShell's
# GetFullPath and Node's path.resolve are both lexical; resolving symlinks here
# would make the sh shipper disagree with the Node one about the same file
# (/private/tmp vs /tmp on macOS) and re-ship it on every alternating run.
#
# But lexical is not the same as untouched, and an earlier version that only
# prefixed $PWD was a real bug: path.resolve and GetFullPath both COLLAPSE
# redundant separators and `.`/`..` segments, so `/logs//claude.log` (what a
# ROGUE_LOG_DIR with a trailing slash produces, and what an MDM-pushed env file
# very plausibly contains) compared unequal to `/logs/claude.log` from the other
# implementation. Each then read the other's state as belonging to a different
# file, reset the offset and re-shipped the whole log - i.e. duplicate lines in the
# dataset, on a machine that merely has two agents installed. The segment walk
# below matches both, so the same file always yields the same string:
#   /a//b/./c/../d -> /a/b/d      /a/b/ -> /a/b      /.. -> /
normalize_path() {
  case "${1:-}" in
    /*) _norm_rest="$1" ;;
    *)  _norm_rest="$PWD/${1:-}" ;;
  esac
  _norm_out=""
  while [ -n "$_norm_rest" ]; do
    _norm_segment="${_norm_rest%%/*}"
    case "$_norm_rest" in
      */*) _norm_rest="${_norm_rest#*/}" ;;
      *)   _norm_rest="" ;;
    esac
    case "$_norm_segment" in
      ''|.) : ;;                                 # // or /./ - nothing to add
      ..)   _norm_out="${_norm_out%/*}" ;;       # at the root this stays ""
      *)    _norm_out="$_norm_out/$_norm_segment" ;;
    esac
  done
  [ -n "$_norm_out" ] || _norm_out="/"
  printf '%s' "$_norm_out"
}

# `wc -c`, never `stat`: BSD and GNU stat take different flags for file size.
file_size() {
  _size_bytes=$(wc -c < "${1:-}" 2>/dev/null | tr -d '[:space:]')
  case "${_size_bytes:-}" in ''|*[!0-9]*) printf '0' ;; *) printf '%s' "$_size_bytes" ;; esac
}

# `tail -c +N` is 1-BASED. Both flags are already load-bearing elsewhere in this
# repo (plugins/copilot/scripts/hook.sh), so this adds no portability assumption.
read_range() { # <file> <offset> <bytes>
  [ "${3:-0}" -gt 0 ] || return 0
  tail -c +$((${2:-0} + 1)) "${1:-}" 2>/dev/null | head -c "${3:-0}" 2>/dev/null
  return 0
}

# Length in BYTES of the first newline-separated record of a file.
# LC_ALL=C so length() counts bytes, not characters.
first_record_length() {
  LC_ALL=C awk 'BEGIN{RS="\n"} { print length($0); exit }' "${1:-}" 2>/dev/null
}

# Bytes AFTER the last \n: 0 when the chunk already ends on a line boundary, the
# whole length when it holds no newline at all.
#
# The obvious one-liner (`awk 'BEGIN{RS="\n"} END{print length($0)}'`) is WRONG on
# its own: with RS="\n", $0 in END is the LAST RECORD, not the text after the final
# separator, so `a\nb\n` yields 1 where it must yield 0 (verified under both awk
# and dash's awk). A chunk trimmed one byte short would leave the offset lagging
# one byte per run forever, and the symptom is a stray leading \n on the next
# chunk rather than an error. So test the final byte first.
trailing_fragment_bytes() {
  if [ "$(tail -c 1 "${1:-}" 2>/dev/null | od -An -tu1 | tr -d ' \n')" = "10" ]; then
    printf '0'
    return 0
  fi
  _fragment_after_last_newline=$(LC_ALL=C awk 'BEGIN{RS="\n"} END{print length($0)}' "${1:-}" 2>/dev/null)
  case "${_fragment_after_last_newline:-}" in
    ''|*[!0-9]*) printf '0' ;;
    *) printf '%s' "$_fragment_after_last_newline" ;;
  esac
}

# base64 of the file's FIRST LINE INCLUDING its newline, or "" when no newline
# exists within the first HEAD_WINDOW_BYTES bytes ("unknown" - the caller then
# falls back to `size < offset` alone).
#
# A LINE, not the first N bytes: logs are append-only, so once a \n exists at byte
# k, bytes 0..k never change again. Fingerprinting a fixed 200 bytes instead
# misfires on a young file - one 60-byte line hashes 60 bytes, and after three
# more lines arrive the same window spans lines 1-3, so the head "changes", the
# offset resets and the file is re-shipped on every run until it passes 200 bytes.
#
# Base64 of a byte range, NOT a checksum: all three implementations share
# ~/.rogue/ship/, so under ROGUE_SHIP_ALL Gemini's .mjs writes state the .sh one
# reads next session. A cksum/CRC would have to be bit-identical across sh,
# PowerShell and Node - reimplementing POSIX cksum twice for no gain - whereas
# base64 of a byte range is identical everywhere by construction.
first_line_fingerprint() {
  _head_window_file="$TMP_DIR/headwin"
  head -c $((HEAD_WINDOW_BYTES + 1)) "${1:-}" > "$_head_window_file" 2>/dev/null
  _head_window_bytes=$(file_size "$_head_window_file")
  [ "$_head_window_bytes" -gt 0 ] || return 0
  _head_first_record_bytes=$(first_record_length "$_head_window_file")
  case "${_head_first_record_bytes:-}" in ''|*[!0-9]*) return 0 ;; esac
  # A first record SHORTER than what we read is the exact, single-pass test for
  # "a newline exists, at byte $_head_first_record_bytes". Equal lengths mean the
  # window held no newline, so the head is unknown.
  [ "$_head_first_record_bytes" -lt "$_head_window_bytes" ] || return 0
  head -c $((_head_first_record_bytes + 1)) "$_head_window_file" 2>/dev/null \
    | base64 2>/dev/null | tr -d '\r\n'
  return 0
}

# ── stage 1: Git Bash stand-down ───────────────────────────────────────────
# ship-logs.ps1 owns native Windows. Git Bash's `~` maps to %USERPROFILE% - the
# SAME ~/.rogue/ship state the ps1 uses - so without this both would ship.
stand_down_on_git_bash() {
  case "$(uname -s 2>/dev/null)" in
    MINGW*|MSYS*|CYGWIN*) debug 'Git Bash -> stand down'; exit 0 ;;
  esac
  return 0
}

# ── stage 2: arguments ─────────────────────────────────────────────────────
parse_args() {
  PLUGIN_ROOT="${1:-}"
  SHIPPER_SLUG="$(trim "${2:-}")"
  SHIPPER_VERSION="$(trim "${3:-}")"
  AGENT_FAMILY="$(trim "${4:-}")"
  if [ -z "$PLUGIN_ROOT" ]; then
    # Self-locate so the BUNDLED env file is still read on a no-argument run.
    PLUGIN_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." 2>/dev/null && pwd)" || PLUGIN_ROOT=""
  fi
  if [ -z "$SHIPPER_SLUG" ]; then
    # No slug -> "ship my own log" is not a question this run can answer, so it
    # means "collect everything" (the support invocation). An earlier draft
    # defaulted the slug to `unknown`, which would look for unknown.log and ship
    # nothing at all.
    SHIPPER_SLUG="unknown"
    SHIP_ALL_LOGS=1
  fi
  [ -n "$SHIPPER_VERSION" ] || SHIPPER_VERSION="unknown"
  return 0
}

# ── stage 3: env files + knobs ─────────────────────────────────────────────
# Same platform-aware rule as every dispatcher: the first trusted env file holding
# ROGUE_API_KEY is used alone, and its values override the process env:
#   /etc/rogue/env (machine, MDM)  ->  <plugin-root>/env  ->  $HOME/.rogue-env
load_env() {
  [ -r "$(dirname "$0")/env-file.sh" ] || return 0
  . "$(dirname "$0")/env-file.sh"
  for _env_file in /etc/rogue/env "$PLUGIN_ROOT/env" "$HOME/.rogue-env"; do
    if rogue_env_is_trusted "$_env_file" && grep -Eq '^[[:space:]]*(export[[:space:]]+)?ROGUE_API_KEY=' "$_env_file" 2>/dev/null; then
      . "$_env_file"; break
    fi
  done
  return 0
}

# A NON-NUMERIC value falls back to the default - a typo must never disable
# shipping or blow a size cap. A leading `-` is non-numeric under the digits-only
# test, so negatives fall back too. ZERO differs per knob: there is no useful
# reading of "a zero-byte upload" (the offset would never advance and the file
# would never drain - a silent permanent stall), while a zero interval genuinely
# means "no throttle" and the documented support one-liner relies on it.
number_or_default() { # <value> <default> <allow-zero:0|1>
  case "${1:-}" in ''|*[!0-9]*) printf '%s' "${2:-0}"; return 0 ;; esac
  # All digits is not the same as representable: `[ "$1" -le 0 ]` on a value
  # wider than a signed 64-bit int makes dash print "Illegal number" to stderr
  # and answer FALSE, so the absurd value would sail through as a byte budget
  # and every later comparison against it would fail the same way. 18 digits is
  # the widest that always fits; strip leading zeros first so a padded zero is
  # still judged on its value. Same clamp the dispatchers apply to
  # ROGUE_LOG_MAX_BYTES, for the same reason.
  _num_digits=$1
  while [ "${_num_digits#0}" != "$_num_digits" ]; do _num_digits="${_num_digits#0}"; done
  if [ "${#_num_digits}" -gt 18 ]; then printf '%s' "${2:-0}"; return 0; fi
  if [ "${3:-0}" != 1 ] && [ "$1" -le 0 ]; then printf '%s' "${2:-0}"; return 0; fi
  printf '%s' "$1"
}

# SHIPPING IS UNCONDITIONAL. There is no ROGUE_SHIP_LOGS flag: a configured install
# uploads its hook log, and the only things that stop a given run are the ones that
# were always able to - no API key, no resolvable actor, the self-throttle, or simply
# no new bytes on disk. It was opt-in while /api/v1/hooks/logs was undeployed, since a
# default-on client would have POSTed into a permanent 404 and appended an
# `outcome=fail http=404` line to the very file it was draining. The route now exists
# (an empty body is answered 422 with a body-schema validation error, where a genuinely
# unknown hooks path is answered a bare 404), so the gate is gone rather than flipped.
#
# What the 2xx contract still requires of the server is unchanged and load-bearing:
# the offset advances only on 2xx and the client then forgets those bytes, so a 2xx
# sent before a durable write is a permanent, silent gap. See
# docs/log-shipping-backend.md.

resolve_knobs() {
  MIN_INTERVAL_SECONDS=$(number_or_default "${ROGUE_SHIP_MIN_INTERVAL:-}" 900 1)
  MAX_CHUNK_BYTES=$(number_or_default "${ROGUE_SHIP_MAX_BYTES:-}" 1048576 0)
  MAX_RUN_BYTES=$(number_or_default "${ROGUE_SHIP_MAX_RUN_BYTES:-}" 10485760 0)
  MAX_LINE_BYTES=$(number_or_default "${ROGUE_SHIP_MAX_LINE_BYTES:-}" 4194304 0)
  # Left as parse_args set it when unset or non-numeric, so a no-argument run
  # keeps its implied ship-everything even if the knob is absent.
  case "${ROGUE_SHIP_ALL:-}" in
    ''|*[!0-9]*) : ;;
    *) [ "$ROGUE_SHIP_ALL" -eq 0 ] || SHIP_ALL_LOGS=1 ;;
  esac
  LOG_DIR="${ROGUE_LOG_DIR:-$HOME/.rogue/logs}"
  EXACT_LOG_FILE="${ROGUE_LOG_FILE:-}"
  [ "$SHIPPER_SLUG" = "unknown" ] || SELF_LOG_FILE="${EXACT_LOG_FILE:-$LOG_DIR/$SHIPPER_SLUG.log}"
  API_KEY="${ROGUE_API_KEY:-}"
  _knobs_base_url="${ROGUE_BASE_URL:-https://api.rogue.security}"
  SHIP_URL="${_knobs_base_url%/}$SHIP_ENDPOINT_PATH"
  return 0
}

# ── stage 4: identity ──────────────────────────────────────────────────────
# The actor is INHERITED, never re-resolved. The shipper deliberately carries NO
# cascade of its own: the six plugins' cascades are not the same (actor.sh falls
# back to `hostname`, Cursor's hook.sh to `$USER@$(hostname)`), so an independent
# re-resolve does not merely risk drift - it produces it, and the heartbeat's
# roster row and this run's log_source row then never meet. Nothing errors; the
# logs just attach to nothing. So: env, else the plugin's own actor.sh, else SKIP.
resolve_actor() { # returns non-zero when there is no identity to ship under
  ACTOR_EMAIL="$(trim "${ROGUE_ACTOR_EMAIL:-}")"
  ACTOR_NAME="$(trim "${ROGUE_ACTOR_NAME:-}")"
  if [ -z "$ACTOR_EMAIL" ]; then
    if [ -r "$PLUGIN_ROOT/scripts/actor.sh" ]; then
      # actor.sh uses ${CLAUDE_CODE_USER_EMAIL%@*} with no default, which aborts
      # under `set -u`; relax nounset across the source exactly as the heartbeats do.
      set +u
      . "$PLUGIN_ROOT/scripts/actor.sh"
      set -u
      ACTOR_EMAIL="$(trim "${ROGUE_ACTOR_EMAIL:-}")"
      ACTOR_NAME="$(trim "${ROGUE_ACTOR_NAME:-}")"
    elif [ -z "$ACTOR_NAME" ]; then
      # Nothing was passed and there is no actor.sh to ask - THAT is the case this
      # skip was written for. A NAME on its own is still an inherited identity, and
      # the PowerShell and Node copies (which have no actor.sh at all, so they land
      # here for every empty email) canonicalize it to `anon` and ship. Returning 1
      # here instead made `plugins/cursor` - the one plugin that ships a shipper but
      # no actor.sh - the only place on a machine where that state shipped nothing.
      return 1
    fi
  fi
  # One canonical form, matching the roster fingerprint's `actorEmail ?? "anon"`
  # extended to cover "" and "   " - which is what a `git config user.email` miss
  # actually yields, since the heartbeat sends an empty string and not JSON null.
  # Deliberately NOT lower-cased: the roster's existing fingerprints were computed
  # on the raw case, so folding it here would re-key every install.
  [ -n "$ACTOR_EMAIL" ] || ACTOR_EMAIL="anon"
  HOST_NAME=$(hostname 2>/dev/null || echo unknown)
  [ -n "$HOST_NAME" ] || HOST_NAME="unknown"
  return 0
}

# ── stage 5: which files ───────────────────────────────────────────────────
# Each plugin's shipper uploads only ITS OWN agent's log. An earlier draft had
# every copy ship all six for coverage; the call-site fix removed the case that
# justified it, and a Cursor-only install uploading another vendor's file is a bad
# line in a security review. ROGUE_SHIP_ALL=1 restores it for support.
list_target_files() {
  if [ -n "$EXACT_LOG_FILE" ]; then
    # ROGUE_LOG_FILE mode: ALL agents write to this one path, so it is the only
    # file regardless of ROGUE_SHIP_ALL.
    printf '%s\n' "$EXACT_LOG_FILE"
    return 0
  fi
  if [ "$SHIP_ALL_LOGS" = 1 ]; then
    for _target_slug in $KNOWN_LOG_SLUGS; do
      [ -f "$LOG_DIR/$_target_slug.log" ] && printf '%s\n' "$LOG_DIR/$_target_slug.log"
    done
    return 0
  fi
  printf '%s\n' "$LOG_DIR/$SHIPPER_SLUG.log"
  return 0
}

# `agent_family` is a FALLBACK HINT, not the key: the server attributes each line
# off its own `provider=` token. It is sent only for the caller's own log, and
# omitted for a foreign log under ROGUE_SHIP_ALL and for a custom ROGUE_LOG_FILE -
# in both of those the file's lines are mixed-provider, so the shipping plugin's
# family would MISLABEL them (a claude line filed under `openai`).
family_for_file() { # <basename>
  [ -z "$EXACT_LOG_FILE" ] || return 0
  [ "${1:-}" = "$SHIPPER_SLUG.log" ] || return 0
  printf '%s' "$AGENT_FAMILY"
  return 0
}

# ── stage 6: throttle, lock ────────────────────────────────────────────────
# Keyed per log file, not globally: a shared stamp would starve every agent but
# whichever started a session first.
state_key_for() { # <path>  -> basename minus a trailing .log
  _state_key_basename=$(basename -- "${1:-}")
  printf '%s' "${_state_key_basename%.log}"
}

now_epoch_seconds() { date -u +%s 2>/dev/null; }

# The throttle is NOT a bandwidth measure - a run with nothing new makes no HTTP
# request at all. It is a crash-loop guard: .last-<key> is stamped the instant the
# lock is taken, BEFORE any upload, so a shipper that dies before persisting its
# offset re-runs at most once per interval instead of on every session start.
within_throttle_window() { # <key> -> 0 when this file should be skipped
  _throttle_stamp_file="$STATE_DIR/.last-${1:-}"
  [ -r "$_throttle_stamp_file" ] || return 1
  _throttle_last_run=$(head -n1 "$_throttle_stamp_file" 2>/dev/null | tr -d '[:space:]')
  case "${_throttle_last_run:-}" in ''|*[!0-9]*) return 1 ;; esac
  _throttle_now=$(now_epoch_seconds)
  case "${_throttle_now:-}" in ''|*[!0-9]*) return 1 ;; esac
  # A stamp in the FUTURE (clock stepped back, bad write) is stale, not a reason
  # to stop shipping until the clock catches up.
  [ "$_throttle_last_run" -gt "$_throttle_now" ] && return 1
  [ $((_throttle_now - _throttle_last_run)) -lt "$MIN_INTERVAL_SECONDS" ] && return 0
  return 1
}

stamp_run_time() {
  printf '%s\n' "$(now_epoch_seconds)" > "$STATE_DIR/.last-${1:-}" 2>/dev/null
  return 0
}

# `mkdir` is a single atomic filesystem operation - succeed, or fail because it
# exists, with no gap. The naive shell version (`[ ! -e lock ] && touch lock`) is
# two operations and both processes can pass the test before either writes.
# New-Item -ItemType Directory fails the same way on Windows, so one design covers
# both. The age marker is a file INSIDE the lock rather than the directory's own
# mtime, because reading mtime portably needs `stat`, whose flags differ between
# BSD and GNU (the same reason phase 1 reads size with `wc -c`).
acquire_lock() { # <key>
  _lock_dir="$STATE_DIR/.lock-${1:-}"
  if mkdir "$_lock_dir" 2>/dev/null; then
    HELD_LOCK_DIR="$_lock_dir"
    printf '%s\n' "$(now_epoch_seconds)" > "$_lock_dir/ts" 2>/dev/null
    return 0
  fi
  [ -d "$_lock_dir" ] || return 1
  # A killed shipper must not wedge the feature permanently. An unreadable or
  # unparseable marker counts as stale: a lock we cannot age out is worse than one
  # we reclaim slightly early.
  _lock_stamp=$(head -n1 "$_lock_dir/ts" 2>/dev/null | tr -d '[:space:]')
  _lock_now=$(now_epoch_seconds)
  _lock_is_stale=1
  case "${_lock_stamp:-}" in
    ''|*[!0-9]*)
      # NO READABLE MARKER IS NOT PROOF OF A DEAD HOLDER. `mkdir` and the `ts` write
      # are two operations, so a lock taken microseconds ago legitimately has no
      # marker yet - and treating that as stale let a second run delete a live lock,
      # take it, and upload the same byte range twice. Age the DIRECTORY instead, via
      # `find -mmin` rather than `stat`, whose flags differ between BSD and GNU (the
      # same portability reason phase 1 reads size with `wc -c`). No output - or a
      # `find` that does not understand the flags - reads as "not old enough", which
      # costs one skipped cycle rather than a duplicate upload.
      if [ -n "$(find "$_lock_dir" -maxdepth 0 -mmin +"$LOCK_STALE_MINUTES" 2>/dev/null)" ]
      then _lock_is_stale=1
      else _lock_is_stale=0
      fi
      ;;
    *) case "${_lock_now:-}" in
         ''|*[!0-9]*) _lock_is_stale=0 ;;
         *) [ "$_lock_stamp" -le "$_lock_now" ] &&
            [ $((_lock_now - _lock_stamp)) -le "$LOCK_STALE_SECONDS" ] && _lock_is_stale=0 ;;
       esac ;;
  esac
  [ "$_lock_is_stale" = 1 ] || return 1
  rm -f "$_lock_dir/ts" 2>/dev/null
  rmdir "$_lock_dir" 2>/dev/null
  if mkdir "$_lock_dir" 2>/dev/null; then
    HELD_LOCK_DIR="$_lock_dir"
    printf '%s\n' "$(now_epoch_seconds)" > "$_lock_dir/ts" 2>/dev/null
    return 0
  fi
  return 1
}

release_lock() {
  [ -n "$HELD_LOCK_DIR" ] || return 0
  rm -f "$HELD_LOCK_DIR/ts" 2>/dev/null
  rmdir "$HELD_LOCK_DIR" 2>/dev/null
  HELD_LOCK_DIR=""
  return 0
}

cleanup() {
  release_lock
  [ -n "$TMP_DIR" ] && rm -rf "$TMP_DIR" 2>/dev/null
  return 0
}

# ── stage 7: state ─────────────────────────────────────────────────────────
read_state() { # <key> <abs-path>
  OFFSET=0; STATE_HEAD=""; STATE_SIZE=0; STATE_PATH=""
  _state_file="$STATE_DIR/${1:-}.state"
  [ -r "$_state_file" ] || return 0
  while IFS= read -r _state_line; do
    case "$_state_line" in
      offset=*)
        _state_value="${_state_line#offset=}"
        case "$_state_value" in ''|*[!0-9]*) _state_value=0 ;; esac
        OFFSET="$_state_value" ;;
      head=*) STATE_HEAD="${_state_line#head=}" ;;
      size=*)
        _state_value="${_state_line#size=}"
        case "$_state_value" in ''|*[!0-9]*) _state_value=0 ;; esac
        STATE_SIZE="$_state_value" ;;
      path=*) STATE_PATH="${_state_line#path=}" ;;
    esac
  done < "$_state_file"
  # The key is a BASENAME, so /a/claude.log and /b/claude.log key alike: changing
  # ROGUE_LOG_DIR (an MDM edit, a relocated home) would otherwise point the
  # shipper at a different file holding the previous file's offset. The head check
  # would turn that into a re-ship rather than silent loss, but detecting it
  # directly is cheaper and clearer.
  if [ -n "$STATE_PATH" ] && [ "$STATE_PATH" != "${2:-}" ]; then
    debug "state path mismatch ($STATE_PATH != ${2:-}) -> treating state as absent"
    OFFSET=0; STATE_HEAD=""; STATE_SIZE=0
  fi
  return 0
}

# write-to-temp-then-mv, so a crash mid-write cannot leave a half-written offset.
# The temp lives in the SAME directory as the destination, or the mv is not atomic.
write_state() { # <key> <offset> <head> <size> <path>
  _state_tmp_file="$STATE_DIR/.state-tmp-$$"
  printf 'offset=%s\nhead=%s\nsize=%s\npath=%s\n' \
    "${2:-0}" "${3:-}" "${4:-0}" "${5:-}" > "$_state_tmp_file" 2>/dev/null || return 0
  mv -f "$_state_tmp_file" "$STATE_DIR/${1:-}.state" 2>/dev/null
  return 0
}

# ── stage 8: chunks ────────────────────────────────────────────────────────
# Bytes from <offset> through the first newline at/after it. Sets LINE_LENGTH (0 =
# not found) and LINE_SEARCH_HIT_EOF (1 = the search reached end of file, so there
# is genuinely nothing more to find).
#
# THE SEARCH SPANS WINDOWS, and that is load-bearing. An earlier version probed a
# single MAX_LINE_BYTES window and, on a miss, advanced the offset by
# MAX_LINE_BYTES and probed again — which lands the offset MID-LINE, and the next
# probe then finds the newline a few bytes ahead and ships the tail of the
# over-long line as if it were a short line. Verified: a 406-byte line against
# ROGUE_SHIP_MAX_LINE_BYTES=100 shipped its last 6 bytes as a chunk. Any advance
# that does not land exactly after a newline makes every subsequent read a
# fragment, so the ONLY safe skip target is the next newline — never a fixed
# window.
#
# Memory stays bounded by reading one window at a time rather than letting `awk`
# buffer a whole record: a multi-megabyte line is the case this function exists for,
# so it must not hold one in memory. Windows overlap by a byte, so no newline can
# fall between two of them.
find_line_end() { # <file> <offset>
  LINE_LENGTH=0; LINE_SEARCH_HIT_EOF=0
  _scan_file="${1:-}"
  _scan_from="${2:-0}"
  _scan_bytes_done=0
  _scan_window_num=0
  while [ "$_scan_window_num" -lt "$MAX_SCAN_WINDOWS" ]; do
    _scan_probe_file="$TMP_DIR/probe"
    read_range "$_scan_file" $((_scan_from + _scan_bytes_done)) $((MAX_LINE_BYTES + 1)) \
      > "$_scan_probe_file" 2>/dev/null
    _scan_probe_bytes=$(file_size "$_scan_probe_file")
    if [ "$_scan_probe_bytes" -eq 0 ]; then LINE_SEARCH_HIT_EOF=1; return 0; fi
    _scan_first_record_bytes=$(first_record_length "$_scan_probe_file")
    case "${_scan_first_record_bytes:-}" in
      ''|*[!0-9]*) _scan_first_record_bytes="$_scan_probe_bytes" ;;
    esac
    # A first record SHORTER than what we read means a newline exists, at
    # $_scan_first_record_bytes.
    if [ "$_scan_first_record_bytes" -lt "$_scan_probe_bytes" ]; then
      LINE_LENGTH=$((_scan_bytes_done + _scan_first_record_bytes + 1))
      return 0
    fi
    # Short read: the window hit EOF without a newline.
    if [ "$_scan_probe_bytes" -le "$MAX_LINE_BYTES" ]; then LINE_SEARCH_HIT_EOF=1; return 0; fi
    _scan_bytes_done=$((_scan_bytes_done + MAX_LINE_BYTES))
    _scan_window_num=$((_scan_window_num + 1))
  done
  return 0
}

# POST one chunk. Sets ADVANCE_BYTES to the bytes the offset should advance by
# (which is NOT always the bytes sent - an over-long line is skipped forward).
# Returns non-zero when nothing was shipped and the offset must NOT move.
ship_next_chunk() { # <file> <offset> <rotated:0|1> <expected-head>
  ADVANCE_BYTES=0
  _chunk_source_file="${1:-}"
  _chunk_offset="${2:-0}"
  _chunk_rotated="${3:-0}"
  _chunk_expected_head="${4:-}"
  _chunk_file_bytes=$(file_size "$_chunk_source_file")
  _chunk_want_bytes=$((_chunk_file_bytes - _chunk_offset))
  [ "$_chunk_want_bytes" -gt 0 ] || return 1
  [ "$_chunk_want_bytes" -le "$MAX_CHUNK_BYTES" ] || _chunk_want_bytes=$MAX_CHUNK_BYTES
  _chunk_tmp_file="$TMP_DIR/chunk"
  read_range "$_chunk_source_file" "$_chunk_offset" "$_chunk_want_bytes" \
    > "$_chunk_tmp_file" 2>/dev/null
  _chunk_bytes=$(file_size "$_chunk_tmp_file")
  [ "$_chunk_bytes" -gt 0 ] || return 1

  # Chunks end on line boundaries. Hitting the cap mid-line would put a line's
  # first half in chunk N and its second in chunk N+1 - two stored events, two
  # corrupt lines instead of one good one - and the same hazard exists at the tail
  # from a torn concurrent append.
  _chunk_fragment_bytes=$(trailing_fragment_bytes "$_chunk_tmp_file")
  _chunk_keep_bytes=$((_chunk_bytes - _chunk_fragment_bytes))
  if [ "$_chunk_keep_bytes" -le 0 ]; then
    ship_oversize_line "$_chunk_source_file" "$_chunk_offset" "$_chunk_rotated" \
      "$_chunk_expected_head" "$_chunk_file_bytes"
    return $?
  fi
  if [ "$_chunk_fragment_bytes" -gt 0 ]; then
    head -c "$_chunk_keep_bytes" "$_chunk_tmp_file" > "$TMP_DIR/trim" 2>/dev/null
    mv -f "$TMP_DIR/trim" "$_chunk_tmp_file" 2>/dev/null
  fi

  # Rotation DURING the read (the TOCTOU). The dispatcher can rename the file
  # between our size read and this read_range, in which case the bytes above came
  # from the NEW file: shipping them labelled offset=<old> loses the old file's
  # real tail and then persists an offset over the top of it. Window is
  # milliseconds and rotation is once per generation, but the corruption is silent
  # and permanent, so re-read the head and discard the chunk if it moved.
  _chunk_head_now=$(first_line_fingerprint "$_chunk_source_file")
  if [ "$_chunk_head_now" != "$_chunk_expected_head" ]; then
    debug "head changed under us -> discarding chunk at $_chunk_offset"
    return 1
  fi
  post_chunk "$_chunk_tmp_file" "$_chunk_offset" "$_chunk_keep_bytes" "$_chunk_rotated" || return 1
  ADVANCE_BYTES=$_chunk_keep_bytes
  return 0
}

# A single line longer than one request. "If the chunk has no newline, ship it
# whole" was incoherent: the chunk was ALREADY truncated to the cap, so "whole"
# shipped a PARTIAL line, contradicting the invariant the server parser depends
# on. Both branches here are unreachable in a healthy install (`raw=` is capped at
# 400 chars), so a multi-megabyte line means something already went wrong - which
# is why the unfindable case SKIPS FORWARD instead of retrying: a corrupt line
# must not park the file forever.
ship_oversize_line() { # <file> <offset> <rotated> <expected-head> <file-size>
  _oversize_source_file="${1:-}"
  _oversize_offset="${2:-0}"
  _oversize_rotated="${3:-0}"
  _oversize_expected_head="${4:-}"
  _oversize_file_bytes="${5:-0}"
  find_line_end "$_oversize_source_file" "$_oversize_offset"
  if [ "$LINE_LENGTH" -gt 0 ]; then
    if [ "$LINE_LENGTH" -le "$MAX_LINE_BYTES" ]; then
      _oversize_tmp_file="$TMP_DIR/chunk"
      read_range "$_oversize_source_file" "$_oversize_offset" "$LINE_LENGTH" \
        > "$_oversize_tmp_file" 2>/dev/null
      _oversize_bytes=$(file_size "$_oversize_tmp_file")
      [ "$_oversize_bytes" -gt 0 ] || return 1
      _oversize_head_now=$(first_line_fingerprint "$_oversize_source_file")
      [ "$_oversize_head_now" = "$_oversize_expected_head" ] || return 1
      post_chunk "$_oversize_tmp_file" "$_oversize_offset" "$_oversize_bytes" \
        "$_oversize_rotated" || return 1
      ADVANCE_BYTES=$_oversize_bytes
      return 0
    fi
    # Over the ceiling: skip PAST ITS NEWLINE, never by a fixed amount, so the new
    # offset lands exactly on the start of the next line.
    log "outcome=skip reason=oversize-line file=$TARGET_BASENAME offset=$_oversize_offset bytes=$LINE_LENGTH"
    ADVANCE_BYTES=$LINE_LENGTH
    return 0
  fi
  # No newline in the window.
  if [ "$LINE_SEARCH_HIT_EOF" = 1 ]; then
    _oversize_remaining_bytes=$((_oversize_file_bytes - _oversize_offset))
    [ "$_oversize_remaining_bytes" -gt 0 ] || return 1
    # A ROTATED generation is frozen, so its unterminated final line is complete
    # and will never grow: send it rather than stalling on .1 forever, which would
    # also stop the live log from ever resetting.
    if [ "$_oversize_rotated" = 1 ]; then
      # The ceiling applies to this tail too. It is a line like any other, and
      # the newline search that produced it may have spanned every scan window -
      # up to MAX_SCAN_WINDOWS * MAX_LINE_BYTES, 256 MiB at the defaults - so
      # without this the branch can post a single body far past the ~1 MiB (4 MiB
      # for one oversized line) the receiver is promised, after allocating it.
      if [ "$_oversize_remaining_bytes" -gt "$MAX_LINE_BYTES" ]; then
        log "outcome=skip reason=oversize-line file=$TARGET_BASENAME offset=$_oversize_offset bytes=$_oversize_remaining_bytes"
        ADVANCE_BYTES=$_oversize_remaining_bytes
        return 0
      fi
      _oversize_tmp_file="$TMP_DIR/chunk"
      read_range "$_oversize_source_file" "$_oversize_offset" "$_oversize_remaining_bytes" \
        > "$_oversize_tmp_file" 2>/dev/null
      # What was READ, not what the size snapshot said: `.1` can be replaced by a
      # fresh rotation between the two, and posting `bytes=` for a length that was
      # never read - then advancing the offset by it - skips real content. The
      # terminated branch above already reads the length back for this reason;
      # PowerShell and Node use their buffer's own length and never had the gap.
      _oversize_bytes=$(file_size "$_oversize_tmp_file")
      [ "$_oversize_bytes" -gt 0 ] || return 1
      post_chunk "$_oversize_tmp_file" "$_oversize_offset" "$_oversize_bytes" \
        "$_oversize_rotated" || return 1
      ADVANCE_BYTES=$_oversize_bytes
      return 0
    fi
    # A LIVE file's unterminated tail is a line still being written. Wait for its
    # newline instead of shipping half of it.
    return 1
  fi
  # The scan bound was exhausted without finding a newline: a single "line" larger
  # than MAX_SCAN_WINDOWS * MAX_LINE_BYTES (256 MiB at the defaults). DO NOT
  # ADVANCE. Landing the offset anywhere other than just after a newline turns
  # every later read into a fragment, so this file stalls until someone looks at
  # it — a diagnostics-loss bug, where advancing would be a corrupt-the-dataset
  # bug. It is logged every run precisely so a stalled file is visible instead of
  # silent.
  log "outcome=stall reason=unbounded-line file=$TARGET_BASENAME offset=$_oversize_offset scanned=$((MAX_LINE_BYTES * MAX_SCAN_WINDOWS))"
  return 1
}

# The chunk NEVER passes through a shell variable: sh variables cannot hold NUL
# bytes and a stray NUL would silently truncate it. The body is streamed to a
# file, so only base64 output (NUL-free by construction) is ever piped - and the
# body is passed as --data-binary @file rather than -d, because a 1 MiB chunk is
# ~1.4 MiB of base64 and macOS's ARG_MAX is 1 MiB for args plus environment.
post_chunk() { # <chunk-file> <offset> <bytes> <rotated:0|1>
  _post_chunk_file="${1:-}"
  _post_offset="${2:-0}"
  _post_bytes="${3:-0}"
  _post_rotated_json='false'
  [ "${4:-0}" = 1 ] && _post_rotated_json='true'
  _post_body_file="$TMP_DIR/body"
  {
    printf '{"host":"%s","actor_email":"%s","actor_name":"%s"' \
      "$(json_escape "$HOST_NAME")" "$(json_escape "$ACTOR_EMAIL")" "$(json_escape "$ACTOR_NAME")"
    [ -n "$TARGET_FAMILY" ] && printf ',"agent_family":"%s"' "$(json_escape "$TARGET_FAMILY")"
    printf ',"shipper":"%s","shipper_version":"%s","log_file":"%s"' \
      "$(json_escape "$SHIPPER_SLUG")" "$(json_escape "$SHIPPER_VERSION")" \
      "$(json_escape "$TARGET_BASENAME")"
    printf ',"offset":%s,"bytes":%s,"rotated":%s,"content_b64":"' \
      "$_post_offset" "$_post_bytes" "$_post_rotated_json"
    base64 < "$_post_chunk_file" 2>/dev/null | tr -d '\r\n'
    printf '"}'
  } > "$_post_body_file" 2>/dev/null
  debug "POST $SHIP_URL file=$TARGET_BASENAME offset=$_post_offset bytes=$_post_bytes rotated=$_post_rotated_json"
  _post_http_code=$(curl -sS --max-time "$HTTP_TIMEOUT" -X POST "$SHIP_URL" \
    -H "x-rogue-api-key: $API_KEY" \
    -H 'Content-Type: application/json' \
    --data-binary @"$_post_body_file" \
    -o /dev/null -w '%{http_code}' 2>/dev/null)
  rm -f "$_post_body_file" 2>/dev/null
  # The offset advances ONLY on 2xx. A non-2xx, a transport failure or a timeout
  # leaves the state untouched, so the same range is re-sent next run: nothing is
  # ever marked exported on unconfirmed data. This makes 2xx load-bearing - it
  # must mean DURABLY ACCEPTED on the server, not merely received.
  case "${_post_http_code:-000}" in
    2??) return 0 ;;
    *) log "outcome=fail file=$TARGET_BASENAME offset=$_post_offset bytes=$_post_bytes http=${_post_http_code:-000}"
       return 1 ;;
  esac
}

# ── stage 9: one log file ──────────────────────────────────────────────────
drain_file() { # <file> <size> <rotated:0|1> <expected-head> <persist-head> <persist-size> <abs>
  _drain_source_file="${1:-}"
  _drain_file_bytes="${2:-0}"
  _drain_rotated="${3:-0}"
  _drain_expected_head="${4:-}"
  _drain_persist_head="${5:-}"
  _drain_persist_size="${6:-0}"
  _drain_persist_path="${7:-}"
  _drain_iteration=0
  while [ "$OFFSET" -lt "$_drain_file_bytes" ]; do
    [ "$RUN_BYTES_SENT" -lt "$MAX_RUN_BYTES" ] || { debug 'run budget spent'; return 1; }
    _drain_iteration=$((_drain_iteration + 1))
    [ "$_drain_iteration" -le "$MAX_CHUNKS_PER_DRAIN" ] || { debug 'iteration guard'; return 1; }
    ship_next_chunk "$_drain_source_file" "$OFFSET" "$_drain_rotated" "$_drain_expected_head" || return 1
    [ "$ADVANCE_BYTES" -gt 0 ] || return 1
    OFFSET=$((OFFSET + ADVANCE_BYTES))
    RUN_BYTES_SENT=$((RUN_BYTES_SENT + ADVANCE_BYTES))
    write_state "$STATE_KEY" "$OFFSET" "$_drain_persist_head" "$_drain_persist_size" "$_drain_persist_path"
  done
  return 0
}

ship_log_file() { # <path>
  _target_file="${1:-}"
  [ -f "$_target_file" ] || { debug "no such log: $_target_file"; return 0; }
  TARGET_BASENAME=$(basename -- "$_target_file")
  TARGET_FAMILY=$(family_for_file "$TARGET_BASENAME")
  STATE_KEY=$(state_key_for "$_target_file")
  [ -n "$STATE_KEY" ] || return 0
  if within_throttle_window "$STATE_KEY"; then debug "throttled: $STATE_KEY"; return 0; fi
  acquire_lock "$STATE_KEY" || { debug "locked: $STATE_KEY"; return 0; }
  # Stamped the instant the lock is taken, BEFORE any upload - that is what makes
  # it a crash-loop guard rather than a bandwidth measure.
  stamp_run_time "$STATE_KEY"

  _target_abs_path=$(normalize_path "$_target_file")
  read_state "$STATE_KEY" "$_target_abs_path"
  _target_file_bytes=$(file_size "$_target_file")
  _target_head=$(first_line_fingerprint "$_target_file")
  RUN_BYTES_SENT=0

  _target_rotated=0
  [ "$_target_file_bytes" -lt "$OFFSET" ] && _target_rotated=1
  if [ -n "$_target_head" ] && [ -n "$STATE_HEAD" ] && [ "$_target_head" != "$STATE_HEAD" ]; then
    _target_rotated=1
  fi

  if [ "$_target_rotated" = 1 ]; then
    debug "rotation detected for $TARGET_BASENAME (size=$_target_file_bytes off=$OFFSET)"
    _target_rotated_file="$_target_file.1"
    if [ -f "$_target_rotated_file" ] && [ -n "$STATE_HEAD" ]; then
      _target_rotated_head=$(first_line_fingerprint "$_target_rotated_file")
      _target_rotated_bytes=$(file_size "$_target_rotated_file")
      # Validating .1's head against the STORED head is what stops a double
      # rotation from re-shipping a generation we already sent. The size floor is
      # an independent second condition: a 4 KiB first-line window is not a
      # digest, so two generations whose first lines are byte-identical would
      # compare equal, and a different generation almost certainly has a
      # different size. (A collision-resistant digest was rejected on
      # portability, not merit - sh has no guaranteed hasher, and the three
      # implementations share this state directory.)
      if [ "$_target_rotated_head" = "$STATE_HEAD" ] && [ "$_target_rotated_bytes" -ge "$STATE_SIZE" ]; then
        # .1 is a WHOLE generation (up to ROGUE_LOG_MAX_BYTES), so it needs the
        # same bounded chunk loop as the live file - one request cannot carry it.
        #
        # A non-zero drain means either a failed upload or a spent run budget, and
        # BOTH must return WITHOUT resetting the offset: resetting mid-.1 would
        # throw away the rest of a rotated generation, which is silent loss. The
        # next run re-detects the rotation and resumes .1 at the stored offset.
        drain_file "$_target_rotated_file" "$_target_rotated_bytes" 1 "$_target_rotated_head" \
          "$STATE_HEAD" "$STATE_SIZE" "$_target_abs_path" || { release_lock; return 0; }
      else
        debug ".1 does not match the stored head -> skipping it"
      fi
    fi
    OFFSET=0
    write_state "$STATE_KEY" 0 "$_target_head" "$_target_file_bytes" "$_target_abs_path"
  fi

  drain_file "$_target_file" "$_target_file_bytes" 0 "$_target_head" \
    "$_target_head" "$_target_file_bytes" "$_target_abs_path"
  release_lock
  return 0
}

# ── main ───────────────────────────────────────────────────────────────────
main() {
  stand_down_on_git_bash
  parse_args "$@"
  load_env
  resolve_knobs
  [ -n "$API_KEY" ] || { debug 'not configured -> no-op'; exit 0; }
  command -v curl >/dev/null 2>&1 || { log 'outcome=fail reason=no-curl'; exit 0; }
  command -v base64 >/dev/null 2>&1 || { log 'outcome=fail reason=no-base64'; exit 0; }
  if ! resolve_actor; then
    # Do NOT invent an identity. A wrong one creates an orphaned log_source row,
    # which is strictly worse than not shipping: the logs are uploaded, billed and
    # stored, and joined to nothing.
    log 'outcome=skip reason=no-actor'
    exit 0
  fi

  STATE_DIR="$HOME/.rogue/ship"
  mkdir -p "$STATE_DIR" 2>/dev/null
  [ -d "$STATE_DIR" ] || { debug "cannot create $STATE_DIR"; exit 0; }
  TMP_DIR=$(mktemp -d "$STATE_DIR/.tmp.XXXXXX" 2>/dev/null) || TMP_DIR=""
  [ -n "$TMP_DIR" ] || { debug 'cannot create a temp dir'; exit 0; }
  trap 'cleanup' EXIT INT TERM

  # A redirect, not a pipe: a `while` on the right of a pipe runs in a subshell in
  # POSIX sh, and log paths can contain spaces, so read them line by line.
  _main_targets_file="$TMP_DIR/targets"
  list_target_files > "$_main_targets_file" 2>/dev/null
  while IFS= read -r _main_target; do
    [ -n "$_main_target" ] || continue
    ship_log_file "$_main_target"
  done < "$_main_targets_file"

  exit 0
}

main "$@"
