# Rogue Security - hook-log shipper (Windows / PowerShell). POSIX sibling:
# ship-logs.sh. Node sibling: plugins/gemini/scripts/ship-logs.mjs.
#
# Uploads the un-shipped tail of this machine's Rogue hook log to
# /api/v1/hooks/logs, so a support engineer can read it WITHOUT an endpoint agent
# on the box. Design, rationale and the state machine: docs/plugin-log-shipper.md.
#
#   ship-logs.ps1 <plugin-root> <shipper-slug> <shipper-version> <agent-family>
#
# NO ARGUMENTS -> collect EVERY known agent's log (ROGUE_SHIP_ALL is implied: with
# no slug there is no "own log" to pick), reporting shipper "unknown".
#
# EDIT scripts/shared/ship-logs.ps1. THIS IS A COMMITTED, BYTE-IDENTICAL COPY of it,
# regenerated by scripts/sync-shared-scripts.sh and verified by
# tests/test_ship_logs.ps1 + `--check` in CI. An edit made here is silently reverted
# by the next sync. (The copies exist, and are committed rather than generated at
# release time, because each plugin installs as a self-contained directory and three
# of them install straight from a git clone with no build step — see the header of
# scripts/sync-shared-scripts.sh.)
#
# Every per-plugin difference is an ARGUMENT; never reference a plugin-specific env
# var here.
#
# Mirrors ship-logs.sh stage for stage so the two can be diffed against each other,
# with three deliberate divergences, each because the sh constraint does not exist
# here:
#   * the chunk lives in a byte[], not a temp file - sh needs the file because sh
#     variables cannot hold NUL bytes, which is not a thing in .NET;
#   * the body is built with ConvertTo-Json -Compress. That is allowed and is NOT
#     what CLAUDE.md forbids: the prohibition is on re-serialising a RELAYED
#     payload (reshaping bytes the server must see verbatim). This body is
#     constructed fresh, so a real serialiser is strictly safer than hand-escaping;
#   * rotation detection reads with FileShare.Delete (see Read-Range).
#
# NAMING: names are spelled out rather than abbreviated, matching ship-logs.sh. The
# sh copy needs a per-function prefix on every temporary because sh has no locals;
# PowerShell function scope makes that unnecessary, so only the SHARED state carries
# the `$script:` qualifier - and it must, or a write from inside a function lands in
# a function-local copy and vanishes with no error (see Initialize-Args).
#
# Fail-open everywhere and always exit 0. PowerShell 5.1-compatible: no `??`, no
# ternaries, no classes.

param(
    [string]$PluginRoot = '',
    [string]$ShipperSlug = '',
    [string]$ShipperVersion = '',
    [string]$AgentFamily = ''
)

$ErrorActionPreference = 'SilentlyContinue'
# Invoke-WebRequest renders a progress bar that, with stdout/stderr redirected
# (always true here), can slow a call 10-50x or effectively hang it.
$ProgressPreference = 'SilentlyContinue'

# ── constants ──────────────────────────────────────────────────────────────
$SHIP_ENDPOINT_PATH = '/api/v1/hooks/logs'
$KNOWN_LOG_SLUGS = @('claude', 'codex', 'cursor', 'gemini', 'copilot', 'antigravity', 'kiro')
# Bytes scanned when fingerprinting a log's first line. NOT 200: a real log line is
# timestamp + provider + event + up to 400 chars of `raw=`, i.e. commonly 500-700
# bytes, so a 200-byte window would find no newline in a typical log's first line
# and the whole rotation check would silently never engage.
$HEAD_WINDOW_BYTES = 4096
# Windows of maxLineBytes scanned when hunting the end of an over-long line: 256 MiB
# at the defaults. Past that the file is not a log any more, and the shipper stalls
# rather than advancing (see Find-LineEnd / Send-OversizeLine).
$MAX_SCAN_WINDOWS = 64
$LOCK_STALE_SECONDS = 600
$MAX_CHUNKS_PER_DRAIN = 64
$HTTP_TIMEOUT = 15

# ── script state (assignments from functions MUST be $script:-qualified, or the
# write lands in a function-local copy and vanishes with no error) ──────────
$script:shipAllLogs = 0
$script:exactLogFile = ''
$script:logDir = ''
$script:stateDir = ''
$script:heldLockDir = ''
$script:selfLogFile = ''
$script:apiKey = ''
$script:shipUrl = ''
$script:hostName = ''
$script:actorEmail = ''
$script:actorName = ''
$script:minIntervalSeconds = 900
$script:maxChunkBytes = 1048576
$script:maxRunBytes = 10485760
$script:maxLineBytes = 4194304
$script:creds = @{}
$script:targetBaseName = ''
$script:targetFamily = ''
$script:stateKey = ''
$script:offset = 0
$script:stateHead = ''
$script:stateSize = 0
$script:statePath = ''
$script:advanceBytes = 0
$script:runBytesSent = 0
$script:lineLength = 0
$script:lineSearchHitEof = 0

function Write-ShipDebug {
    param([string]$Message)
    if ($env:ROGUE_DEBUG) { [Console]::Error.WriteLine("[rogue-ship] $Message") }
}

# Our own diagnostics land in the SHIPPING plugin's log file, tagged
# `event=ShipLogs`, and ONLY for notable outcomes (a failure or a skip) - never on
# the happy path, because a line per run would mean every run has new bytes to
# ship, destroying the "an idle machine makes no HTTP request at all" property that
# makes the throttle cheap. It also lands in the file that gets uploaded, so the
# failure it describes becomes readable once shipping recovers.
#
# The shipper NEVER rotates that file even if its own line pushes it over the cap:
# renaming a log we may be part-way through reading is exactly the
# rotation-under-us hazard Get-FirstLineFingerprint re-checks for. Rotation stays
# the dispatcher's job, on its next write.
#
# AppendAllText with an explicit BOM-less UTF-8, never `Add-Content -Encoding
# UTF8`: on Windows PowerShell 5.1 that switch writes a UTF-8 BOM when it creates
# the file, so the first line would start EF BB BF and break any parser anchored on
# the timestamp. "`n" keeps the line ending identical to the sh dispatchers'.
function Write-ShipLog {
    param([string]$Message)
    # ALSO to stderr under ROGUE_DEBUG, and unconditionally - before the selfLogFile
    # gate below. The no-argument support invocation has no slug, so it has no log
    # file of its own to write to, and every failure reason (`http=<code>`,
    # `reason=no-actor`) used to vanish on exactly the run a support engineer is told
    # to make. The file is where the outcome is durable; stderr is where it is visible.
    Write-ShipDebug $Message
    try {
        if (-not $script:selfLogFile) { return }
        $logParentDir = Split-Path $script:selfLogFile
        if ($logParentDir -and -not (Test-Path -LiteralPath $logParentDir)) {
            New-Item -ItemType Directory -Path $logParentDir -Force | Out-Null
        }
        $timeStamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
        [System.IO.File]::AppendAllText(
            $script:selfLogFile,
            "$timeStamp provider=$ShipperSlug event=ShipLogs $Message`n",
            (New-Object System.Text.UTF8Encoding($false)))
    } catch {}
}

function ConvertFrom-ShellQuoted {
    # Decode one shell "word" the way ship-logs.sh would when it sources the env
    # file, so values round-trip across both. The files are written either POSIX
    # single-quoted with '\'' escapes (setup.ps1) or via bash printf %q (setup.sh).
    param([string]$Value)
    if ($null -eq $Value) { return $Value }
    $decoded = [System.Text.StringBuilder]::new()
    $index = 0
    $length = $Value.Length
    $state = 'normal'
    while ($index -lt $length) {
        $char = $Value[$index]
        switch ($state) {
            'single' { if ($char -eq "'") { $state = 'normal' } else { [void]$decoded.Append($char) } }
            'double' {
                if ($char -eq '"') { $state = 'normal' }
                elseif ($char -eq '\' -and ($index + 1) -lt $length -and ('"\$`'.IndexOf($Value[$index+1]) -ge 0)) {
                    [void]$decoded.Append($Value[$index+1]); $index++
                }
                else { [void]$decoded.Append($char) }
            }
            default {
                if ($char -eq "'") { $state = 'single' }
                elseif ($char -eq '"') { $state = 'double' }
                elseif ($char -eq '\' -and ($index + 1) -lt $length) { [void]$decoded.Append($Value[$index+1]); $index++ }
                else { [void]$decoded.Append($char) }
            }
        }
        $index++
    }
    return $decoded.ToString()
}

function Get-UserHome {
    $userHome = $env:USERPROFILE
    if (-not $userHome) { $userHome = $HOME }
    if (-not $userHome) { $userHome = '.' }
    return $userHome
}

function Get-EpochSeconds {
    $epoch = New-Object DateTime(1970, 1, 1, 0, 0, 0, [DateTimeKind]::Utc)
    return [int64][Math]::Floor(((Get-Date).ToUniversalTime() - $epoch).TotalSeconds)
}

# Lexical normalisation ONLY - no symlink resolution. `path=` in the state file is
# compared as a STRING by all three implementations, and Node's path.resolve is
# lexical too; resolving links here would make two shippers disagree about the same
# file and re-ship it on alternating runs.
#
# GetFullPath does the same collapsing of redundant separators and `.`/`..`
# segments that path.resolve does, which is what the sh copy had to grow a segment
# walk to match: a bare $PWD-prefix there left `/logs//claude.log` unequal to
# `/logs/claude.log`, so each shipper read the other's state as a DIFFERENT FILE,
# reset the offset and re-shipped the whole log. Never replace this with string
# concatenation.
function Get-NormalizedPath {
    param([string]$Path)
    try { return [System.IO.Path]::GetFullPath($Path) } catch { return $Path }
}

function Get-FileLength {
    param([string]$Path)
    try {
        $fileInfo = Get-Item -LiteralPath $Path -ErrorAction SilentlyContinue
        if ($fileInfo -and -not $fileInfo.PSIsContainer) { return [int64]$fileInfo.Length }
    } catch {}
    return [int64]0
}

# Read [Offset, Offset+Count) as raw bytes. Both share flags are load-bearing and
# for OPPOSITE reasons:
#   * FileShare.ReadWrite, or the read fails intermittently whenever a dispatcher
#     is appending;
#   * FileShare.Delete, or holding the file open makes the dispatcher's Move-Item
#     rotation FAIL - and phase 1 swallows that under -ErrorAction
#     SilentlyContinue, so the log would grow past its cap forever. A log shipper
#     causing unbounded log growth is the worst outcome in this design.
function Read-Range {
    param([string]$Path, [int64]$Offset, [int]$Count)
    # An empty byte[], NOT `, @()` - that returns a one-element array wrapping an
    # empty array, so every downstream .Length check reads 1.
    if ($Count -le 0) { return (New-Object byte[] 0) }
    $stream = $null
    try {
        $buffer = New-Object byte[] $Count
        $stream = New-Object System.IO.FileStream(
            $Path,
            [System.IO.FileMode]::Open,
            [System.IO.FileAccess]::Read,
            ([System.IO.FileShare]::ReadWrite -bor [System.IO.FileShare]::Delete))
        [void]$stream.Seek($Offset, [System.IO.SeekOrigin]::Begin)
        $bytesRead = 0
        while ($bytesRead -lt $Count) {
            $justRead = $stream.Read($buffer, $bytesRead, $Count - $bytesRead)
            if ($justRead -le 0) { break }
            $bytesRead += $justRead
        }
        if ($bytesRead -eq $Count) { return $buffer }
        $shortBuffer = New-Object byte[] $bytesRead
        if ($bytesRead -gt 0) { [Array]::Copy($buffer, 0, $shortBuffer, 0, $bytesRead) }
        return $shortBuffer
    } catch {
        return $null
    } finally {
        if ($stream) { $stream.Dispose() }
    }
}

# Bytes AFTER the last 0x0A: 0 when the chunk already ends on a line boundary, the
# whole length when it holds no newline at all.
function Get-TrailingFragmentLength {
    param([byte[]]$Bytes)
    if (-not $Bytes -or $Bytes.Length -eq 0) { return 0 }
    for ($index = $Bytes.Length - 1; $index -ge 0; $index--) {
        if ($Bytes[$index] -eq 10) { return ($Bytes.Length - 1 - $index) }
    }
    return $Bytes.Length
}

# base64 of the file's FIRST LINE INCLUDING its newline, or '' when no newline
# exists within the first HEAD_WINDOW_BYTES bytes ("unknown" - the caller then falls
# back to `size < offset` alone).
#
# A LINE, not a fixed prefix: logs are append-only, so once a newline exists at
# byte k, bytes 0..k never change again. A fixed 200-byte window instead misfires
# on a young file - one short line hashes N bytes, and once more lines arrive the
# same window spans several, so the head "changes", the offset resets and the file
# is re-shipped every run.
#
# base64 of a byte range, NOT a checksum: all three implementations share
# ~/.rogue/ship/, and a CRC would have to be bit-identical across sh, PowerShell
# and Node, whereas base64 of a byte range is identical everywhere by construction.
function Get-FirstLineFingerprint {
    param([string]$Path)
    $headWindow = Read-Range $Path 0 ($HEAD_WINDOW_BYTES + 1)
    if (-not $headWindow -or $headWindow.Length -eq 0) { return '' }
    $newlineIndex = [Array]::IndexOf($headWindow, [byte]10)
    if ($newlineIndex -lt 0) { return '' }
    $firstLine = New-Object byte[] ($newlineIndex + 1)
    [Array]::Copy($headWindow, 0, $firstLine, 0, $newlineIndex + 1)
    return [Convert]::ToBase64String($firstLine)
}

# ── stage 1: stand down on non-Windows ─────────────────────────────────────
# ship-logs.sh owns macOS/Linux/WSL; this owns native Windows. Exactly one runs.
function Test-ShouldStandDown {
    if ($PSVersionTable.PSVersion.Major -ge 6 -and -not $IsWindows) { return $true }
    return $false
}

# ── stage 2: arguments ─────────────────────────────────────────────────────
function Initialize-Args {
    # param() variables live in the SCRIPT scope, so $script:ShipperSlug and
    # $ShipperSlug are the same variable - which is why these writes must be
    # $script:-qualified. A bare `$ShipperSlug = …` inside a function creates a
    # function-local copy that vanishes on return, with no error and no symptom
    # until every envelope reports the wrong slug.
    if (-not $script:PluginRoot) {
        # Self-locate so the BUNDLED env file is still read on a no-argument run.
        # $PSCommandPath is empty under [scriptblock]::Create, so fall back to cwd.
        if ($PSCommandPath) { $script:PluginRoot = Split-Path (Split-Path $PSCommandPath -Parent) -Parent }
        else { try { $script:PluginRoot = (Get-Location).Path } catch { $script:PluginRoot = '.' } }
    }
    $script:ShipperSlug = ([string]$script:ShipperSlug).Trim()
    if (-not $script:ShipperSlug) {
        # No slug -> "ship my own log" is not a question this run can answer, so it
        # means "collect everything" (the support invocation). Defaulting the slug
        # to `unknown` instead would look for unknown.log and ship nothing at all.
        $script:ShipperSlug = 'unknown'
        $script:shipAllLogs = 1
    }
    $script:ShipperVersion = ([string]$script:ShipperVersion).Trim()
    if (-not $script:ShipperVersion) { $script:ShipperVersion = 'unknown' }
    $script:AgentFamily = ([string]$script:AgentFamily).Trim()
}

# ── stage 3: env files + knobs ─────────────────────────────────────────────
# Same rule as every dispatcher: the first trusted env file holding ROGUE_API_KEY
# is used alone, and its values override the process env:
#   C:\ProgramData\rogue\env (machine, MDM)  ->  <plugin-root>\env  ->  %USERPROFILE%\.rogue-env
$SHIP_ENV_VARS = @(
    'ROGUE_API_KEY', 'ROGUE_BASE_URL', 'ROGUE_ACTOR_EMAIL', 'ROGUE_ACTOR_NAME',
    'ROGUE_LOG_FILE', 'ROGUE_LOG_DIR', 'ROGUE_SHIP_MIN_INTERVAL',
    'ROGUE_SHIP_MAX_BYTES', 'ROGUE_SHIP_MAX_RUN_BYTES', 'ROGUE_SHIP_MAX_LINE_BYTES',
    'ROGUE_SHIP_ALL')

function Import-ShipEnv {
    $envLibrary = Join-Path $PluginRoot 'scripts/env-file.ps1'
    if ($PSCommandPath) { $envLibrary = Join-Path (Split-Path -Parent $PSCommandPath) 'env-file.ps1' }
    . ([scriptblock]::Create((Get-Content -Raw -LiteralPath $envLibrary)))
    $resolved = @{}
    foreach ($varName in $SHIP_ENV_VARS) {
        $processValue = [Environment]::GetEnvironmentVariable($varName)
        if ($processValue) { $resolved[$varName] = $processValue }
    }
    $envFiles = @(
        'C:\ProgramData\rogue\env',
        (Join-Path $PluginRoot 'env'),
        (Join-Path (Get-UserHome) '.rogue-env'))
    foreach ($envFile in $envFiles) {
        if (-not $envFile -or -not (Test-Path -LiteralPath $envFile)) { continue }
        $fileVals = @{}
        foreach ($line in (Read-RogueEnvFile $envFile)) {
            if ($line -match '^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$') {
                $fileVals[$Matches[1]] = ConvertFrom-ShellQuoted ($Matches[2].Trim())
            }
        }
        if (-not $fileVals['ROGUE_API_KEY']) { continue }
        foreach ($varName in $fileVals.Keys) { $resolved[$varName] = $fileVals[$varName] }
        break
    }
    $script:creds = $resolved
}

# A NON-NUMERIC value falls back to the default - a typo must never disable
# shipping or blow a size cap. ZERO differs per knob: there is no useful reading of
# "a zero-byte upload" (the offset would never advance and the file would never
# drain - a silent permanent stall), while a zero interval genuinely means "no
# throttle" and the documented support one-liner relies on it.
function Get-NumberOrDefault {
    param([string]$Value, [int64]$Default, [int]$AllowZero = 0)
    if ($Value -notmatch '^[0-9]+$') { return $Default }
    # TryParse, not a cast: [int64] on an all-digit value wider than 64 bits
    # raises "Value was either too large or too small for an Int64", and this
    # script runs under $ErrorActionPreference = 'SilentlyContinue', so the
    # error would vanish and $parsed would stay $null - which then compares as
    # less than everything. Fall back to the default instead, matching the sh
    # copy's 18-digit clamp.
    $parsed = [int64]0
    if (-not [int64]::TryParse($Value, [ref]$parsed)) { return $Default }
    if ($AllowZero -ne 1 -and $parsed -le 0) { return $Default }
    return $parsed
}

# SHIPPING IS UNCONDITIONAL. There is no ROGUE_SHIP_LOGS flag: a configured install
# uploads its hook log, and the only things that stop a given run are the ones that
# were always able to - no API key, no resolvable actor, the self-throttle, or simply
# no new bytes on disk. It was opt-in while /api/v1/hooks/logs was undeployed, since a
# default-on client would have POSTed into a permanent 404 and appended an
# `outcome=fail http=404` line to the very file it was draining. The route now exists
# (an empty body is answered 422 with a body-schema validation error, where a genuinely
# unknown hooks path is answered a bare 404), so the gate is gone rather than flipped.
#
# What the 2xx contract still requires of the server is unchanged and load-bearing:
# the offset advances only on 2xx and the client then forgets those bytes, so a 2xx
# sent before a durable write is a permanent, silent gap. See
# docs/log-shipping-backend.md.

function Resolve-Knobs {
    $script:minIntervalSeconds = Get-NumberOrDefault $script:creds['ROGUE_SHIP_MIN_INTERVAL'] 900 1
    $script:maxChunkBytes      = Get-NumberOrDefault $script:creds['ROGUE_SHIP_MAX_BYTES'] 1048576 0
    $script:maxRunBytes        = Get-NumberOrDefault $script:creds['ROGUE_SHIP_MAX_RUN_BYTES'] 10485760 0
    $script:maxLineBytes       = Get-NumberOrDefault $script:creds['ROGUE_SHIP_MAX_LINE_BYTES'] 4194304 0
    # PowerShell-only clamp, and a deliberate divergence from ship-logs.sh: .NET's
    # FileStream.Read takes an int32 count, so a knob above int32 range would throw
    # at parameter binding instead of shipping. sh arithmetic is 64-bit and needs no
    # equivalent, so this guard would be dead code there. 256 MiB is far above any
    # sane setting and far below the overflow.
    $intCeiling = 268435456
    if ($script:maxChunkBytes -gt $intCeiling) { $script:maxChunkBytes = 1048576 }
    if ($script:maxLineBytes -gt $intCeiling) { $script:maxLineBytes = 4194304 }
    # Left as Initialize-Args set it when unset or non-numeric, so a no-argument run
    # keeps its implied ship-everything.
    $shipAllValue = [string]$script:creds['ROGUE_SHIP_ALL']
    if ($shipAllValue -match '^[0-9]+$' -and [int64]$shipAllValue -ne 0) { $script:shipAllLogs = 1 }

    $configuredLogDir = $script:creds['ROGUE_LOG_DIR']
    if (-not $configuredLogDir) { $configuredLogDir = Join-Path (Join-Path (Get-UserHome) '.rogue') 'logs' }
    $script:logDir = $configuredLogDir
    $script:exactLogFile = [string]$script:creds['ROGUE_LOG_FILE']
    if ($ShipperSlug -ne 'unknown') {
        if ($script:exactLogFile) { $script:selfLogFile = $script:exactLogFile }
        else { $script:selfLogFile = Join-Path $script:logDir "$ShipperSlug.log" }
    }
    $script:apiKey = [string]$script:creds['ROGUE_API_KEY']
    $baseUrl = [string]$script:creds['ROGUE_BASE_URL']
    if (-not $baseUrl) { $baseUrl = 'https://api.rogue.security' }
    $script:shipUrl = $baseUrl.TrimEnd('/') + $SHIP_ENDPOINT_PATH
}

# ── stage 4: identity ──────────────────────────────────────────────────────
# The actor is INHERITED, never re-resolved. The shipper deliberately carries NO
# cascade of its own: the six plugins' cascades are not the same (actor.sh falls
# back to `hostname`, Cursor's hook.sh to "$USER@$(hostname)"), so an independent
# re-resolve does not merely risk drift - it produces it, and the heartbeat's roster
# row and this run's log_source row then never meet. Nothing errors; the logs just
# attach to nothing.
#
# There is no PowerShell actor.sh to fall back to (it is a POSIX shell script), so
# on this platform an absent inherited value is simply a skip. That is the correct
# failure: a wrong identity uploads, bills and stores logs that join to nothing.
# `anon` is the SAME canonical form ship-logs.sh and ship-logs.mjs use, and the
# divergence here was real: this returned $false for an absent, empty or
# whitespace-only email, so a WINDOWS machine whose `git config user.email` is unset
# shipped nothing while the identical POSIX machine shipped under `anon`. The value
# matters because it is the roster fingerprint's own fallback (`actorEmail ?? "anon"`),
# so it joins to the row the heartbeat already created.
#
# The skip below now covers only the case it was written for: no identity was PASSED at
# all, i.e. neither key is present in the resolved map. An empty string is a
# resolved-and-missing email, which `anon` names exactly. (A process-env value of ''
# never reaches the map - Import-ShipEnv only copies truthy ones - so, as in the Node
# copy, "absent" and "exported empty" are deliberately the same case.)
function Resolve-ShipActor {
    if (-not $script:creds.ContainsKey('ROGUE_ACTOR_EMAIL') -and
        -not $script:creds.ContainsKey('ROGUE_ACTOR_NAME')) { return $false }
    $script:actorEmail = ([string]$script:creds['ROGUE_ACTOR_EMAIL']).Trim()
    $script:actorName = ([string]$script:creds['ROGUE_ACTOR_NAME']).Trim()
    if (-not $script:actorEmail) { $script:actorEmail = 'anon' }
    $script:hostName = $env:COMPUTERNAME
    if (-not $script:hostName) {
        try { $script:hostName = [System.Net.Dns]::GetHostName() } catch { $script:hostName = 'unknown' }
    }
    if (-not $script:hostName) { $script:hostName = 'unknown' }
    return $true
}

# ── stage 5: which files ───────────────────────────────────────────────────
# Each plugin's shipper uploads only ITS OWN agent's log; ROGUE_SHIP_ALL=1 restores
# the collect-everything behaviour for support.
function Get-TargetLogFiles {
    if ($script:exactLogFile) {
        # ROGUE_LOG_FILE mode: ALL agents write to this one path, so it is the only
        # file regardless of ROGUE_SHIP_ALL.
        return @($script:exactLogFile)
    }
    if ($script:shipAllLogs -eq 1) {
        $found = @()
        foreach ($knownSlug in $KNOWN_LOG_SLUGS) {
            $candidate = Join-Path $script:logDir "$knownSlug.log"
            if (Test-Path -LiteralPath $candidate) { $found += $candidate }
        }
        return $found
    }
    return @((Join-Path $script:logDir "$ShipperSlug.log"))
}

# `agent_family` is a FALLBACK HINT, not the key: the server attributes each line
# off its own `provider=` token. Sent only for the caller's own log, and omitted
# for a foreign log under ROGUE_SHIP_ALL and for a custom ROGUE_LOG_FILE - in both
# of those the file's lines are mixed-provider, so the shipping plugin's family
# would MISLABEL them (a claude line filed under `openai`).
function Get-FamilyForFile {
    param([string]$BaseName)
    if ($script:exactLogFile) { return '' }
    if ($BaseName -ne "$ShipperSlug.log") { return '' }
    return [string]$AgentFamily
}

# ── stage 6: throttle, lock ────────────────────────────────────────────────
function Get-StateKeyForPath {
    param([string]$Path)
    $baseName = Split-Path $Path -Leaf
    if ($baseName -match '\.log$') { return $baseName.Substring(0, $baseName.Length - 4) }
    return $baseName
}

# The throttle is NOT a bandwidth measure - a run with nothing new makes no HTTP
# request at all. It is a crash-loop guard: the stamp is written the instant the
# lock is taken, BEFORE any upload, so a shipper that dies before persisting its
# offset re-runs at most once per interval instead of on every session start.
function Test-WithinThrottleWindow {
    param([string]$Key)
    $stampFile = Join-Path $script:stateDir ".last-$Key"
    if (-not (Test-Path -LiteralPath $stampFile)) { return $false }
    $rawStamp = ''
    try { $rawStamp = (Get-Content -LiteralPath $stampFile -TotalCount 1 | Out-String).Trim() } catch { return $false }
    if ($rawStamp -notmatch '^[0-9]+$') { return $false }
    $lastRun = [int64]$rawStamp
    $now = Get-EpochSeconds
    # A stamp in the FUTURE (clock stepped back, a bad write) is stale, not a reason
    # to stop shipping until the clock catches up.
    if ($lastRun -gt $now) { return $false }
    return (($now - $lastRun) -lt $script:minIntervalSeconds)
}

function Set-RunTimeStamp {
    param([string]$Key)
    try {
        [System.IO.File]::WriteAllText(
            (Join-Path $script:stateDir ".last-$Key"),
            ((Get-EpochSeconds).ToString() + "`n"),
            (New-Object System.Text.UTF8Encoding($false)))
    } catch {}
}

# Creating a DIRECTORY is a single atomic filesystem operation - succeed, or fail
# because it exists, with no gap. The naive version (test then create) is two
# operations and both processes can pass the test before either writes. The age
# marker is a file INSIDE the lock rather than the directory's own mtime, so the sh
# and PowerShell halves agree without either needing `stat`.
function Lock-StateKey {
    param([string]$Key)
    $lockDir = Join-Path $script:stateDir ".lock-$Key"
    if (-not (Test-Path -LiteralPath $lockDir)) {
        $created = $null
        try { $created = New-Item -ItemType Directory -Path $lockDir -ErrorAction Stop } catch { $created = $null }
        if ($created) {
            $script:heldLockDir = $lockDir
            try {
                [System.IO.File]::WriteAllText((Join-Path $lockDir 'ts'),
                    ((Get-EpochSeconds).ToString() + "`n"),
                    (New-Object System.Text.UTF8Encoding($false)))
            } catch {}
            return $true
        }
    }
    if (-not (Test-Path -LiteralPath $lockDir)) { return $false }
    # A killed shipper must not wedge the feature permanently. An unreadable or
    # unparseable marker counts as stale: a lock we cannot age out is worse than one
    # reclaimed slightly early.
    $isStale = $true
    $rawStamp = ''
    try { $rawStamp = (Get-Content -LiteralPath (Join-Path $lockDir 'ts') -TotalCount 1 | Out-String).Trim() } catch { $rawStamp = '' }
    if ($rawStamp -match '^[0-9]+$') {
        $lockStamp = [int64]$rawStamp
        $now = Get-EpochSeconds
        if ($lockStamp -le $now -and ($now - $lockStamp) -le $LOCK_STALE_SECONDS) { $isStale = $false }
    } else {
        # NO READABLE MARKER IS NOT PROOF OF A DEAD HOLDER. Creating the directory and
        # writing `ts` are two operations, so a lock taken milliseconds ago legitimately
        # has no marker yet - and treating that as stale let a second run delete a live
        # lock, take it, and upload the same byte range twice. Age the DIRECTORY
        # instead. Its own timestamp is free here, unlike the sh copy, which has to
        # shell out to `find` because `stat`'s flags differ between BSD and GNU.
        # An unreadable timestamp reads as "not old enough": one skipped cycle rather
        # than a duplicate upload.
        $isStale = $false
        try {
            $lockAgeSeconds = ((Get-Date).ToUniversalTime() -
                (Get-Item -LiteralPath $lockDir -ErrorAction Stop).LastWriteTimeUtc).TotalSeconds
            if ($lockAgeSeconds -gt $LOCK_STALE_SECONDS) { $isStale = $true }
        } catch {}
    }
    if (-not $isStale) { return $false }
    try { Remove-Item -LiteralPath $lockDir -Recurse -Force -ErrorAction SilentlyContinue } catch {}
    $created = $null
    try { $created = New-Item -ItemType Directory -Path $lockDir -ErrorAction Stop } catch { $created = $null }
    if (-not $created) { return $false }
    $script:heldLockDir = $lockDir
    try {
        [System.IO.File]::WriteAllText((Join-Path $lockDir 'ts'),
            ((Get-EpochSeconds).ToString() + "`n"),
            (New-Object System.Text.UTF8Encoding($false)))
    } catch {}
    return $true
}

function Unlock-StateKey {
    if (-not $script:heldLockDir) { return }
    try { Remove-Item -LiteralPath $script:heldLockDir -Recurse -Force -ErrorAction SilentlyContinue } catch {}
    $script:heldLockDir = ''
}

# ── stage 7: state ─────────────────────────────────────────────────────────
function Read-ShipState {
    param([string]$Key, [string]$NormalizedPath)
    $script:offset = 0; $script:stateHead = ''; $script:stateSize = 0; $script:statePath = ''
    $stateFile = Join-Path $script:stateDir "$Key.state"
    if (-not (Test-Path -LiteralPath $stateFile)) { return }
    try {
        foreach ($line in (Get-Content -LiteralPath $stateFile)) {
            # CAPTURE BEFORE THE SECOND -match. $Matches is a single automatic
            # variable that every -match overwrites, and '^[0-9]+$' has no capture
            # group, so testing `$Matches[1] -match …` and THEN reading $Matches[1]
            # reads the inner match's group 1, which does not exist. That is not
            # theoretical: it made offset and size parse as 0 on every run, so
            # Windows re-shipped each log from byte 0 forever - unbounded duplicate
            # data, silently, with the state file on disk looking perfectly correct.
            # Caught by tests/test_ship_logs.ps1, which is the reason that file exists.
            if ($line -match '^offset=(.*)$') {
                $rawOffset = $Matches[1]
                if ($rawOffset -match '^[0-9]+$') { $script:offset = [int64]$rawOffset } else { $script:offset = 0 }
            } elseif ($line -match '^head=(.*)$') {
                $script:stateHead = $Matches[1]
            } elseif ($line -match '^size=(.*)$') {
                $rawSize = $Matches[1]
                if ($rawSize -match '^[0-9]+$') { $script:stateSize = [int64]$rawSize } else { $script:stateSize = 0 }
            } elseif ($line -match '^path=(.*)$') {
                $script:statePath = $Matches[1]
            }
        }
    } catch { return }
    # The key is a BASENAME, so \a\claude.log and \b\claude.log key alike: changing
    # ROGUE_LOG_DIR (an MDM edit, a relocated profile) would otherwise point the
    # shipper at a different file holding the previous file's offset.
    if ($script:statePath -and $script:statePath -ne $NormalizedPath) {
        Write-ShipDebug "state path mismatch ($($script:statePath) != $NormalizedPath) -> treating state as absent"
        $script:offset = 0; $script:stateHead = ''; $script:stateSize = 0
    }
}

# Write-to-temp-then-move, so a crash mid-write cannot leave a half-written offset.
# The temp sits in the SAME directory as the destination. The destination is removed
# first: `Move-Item -Force` onto an existing file is not reliable on Windows
# PowerShell 5.1, and under -ErrorAction SilentlyContinue a failure there would
# silently freeze the offset forever.
function Write-ShipState {
    param([string]$Key, [int64]$Offset, [string]$Head, [int64]$Size, [string]$Path)
    try {
        $destination = Join-Path $script:stateDir "$Key.state"
        $tempFile = Join-Path $script:stateDir (".state-tmp-" + $PID)
        [System.IO.File]::WriteAllText(
            $tempFile,
            "offset=$Offset`nhead=$Head`nsize=$Size`npath=$Path`n",
            (New-Object System.Text.UTF8Encoding($false)))
        Remove-Item -LiteralPath $destination -Force -ErrorAction SilentlyContinue
        Move-Item -LiteralPath $tempFile -Destination $destination -Force -ErrorAction SilentlyContinue
    } catch {}
}

# ── stage 8: chunks ────────────────────────────────────────────────────────
# Bytes from Offset through the first newline at/after it. Sets lineLength (0 = not
# found) and lineSearchHitEof (1 = the search reached end of file).
#
# THE SEARCH SPANS WINDOWS, and that is load-bearing. An earlier version probed a
# single maxLineBytes window and, on a miss, advanced the offset by maxLineBytes and
# probed again — which lands the offset MID-LINE, so the next probe finds the newline
# a few bytes ahead and ships the TAIL of the over-long line as if it were a short
# line. Verified on the sh side: a 406-byte line against ROGUE_SHIP_MAX_LINE_BYTES=100
# shipped its last 6 bytes as a chunk. Any advance that does not land exactly after
# a newline makes every subsequent read a fragment, so the only safe skip target is
# the next newline. Windows overlap by a byte, so no newline falls between two.
function Find-LineEnd {
    param([string]$Path, [int64]$Offset)
    $script:lineLength = 0; $script:lineSearchHitEof = 0
    $bytesScanned = [int64]0
    for ($window = 0; $window -lt $MAX_SCAN_WINDOWS; $window++) {
        $probe = Read-Range $Path ($Offset + $bytesScanned) ([int]($script:maxLineBytes + 1))
        if ($null -eq $probe -or $probe.Length -eq 0) { $script:lineSearchHitEof = 1; return }
        $newlineIndex = [Array]::IndexOf($probe, [byte]10)
        if ($newlineIndex -ge 0) { $script:lineLength = $bytesScanned + $newlineIndex + 1; return }
        # Short read: the window hit EOF without a newline.
        if ($probe.Length -le $script:maxLineBytes) { $script:lineSearchHitEof = 1; return }
        $bytesScanned += $script:maxLineBytes
    }
}

# POST one chunk. Sets advanceBytes to the bytes the offset should advance by (which
# is NOT always the bytes sent - an over-long line is skipped forward). Returns
# $false when nothing was shipped and the offset must NOT move.
function Send-NextChunk {
    param([string]$Path, [int64]$Offset, [int]$Rotated, [string]$ExpectedHead)
    $script:advanceBytes = 0
    $fileBytes = Get-FileLength $Path
    $wantBytes = $fileBytes - $Offset
    if ($wantBytes -le 0) { return $false }
    if ($wantBytes -gt $script:maxChunkBytes) { $wantBytes = $script:maxChunkBytes }
    $chunk = Read-Range $Path $Offset ([int]$wantBytes)
    if ($null -eq $chunk -or $chunk.Length -eq 0) { return $false }

    # Chunks end on line boundaries. Hitting the cap mid-line would put a line's
    # first half in chunk N and its second in chunk N+1 - two stored events, two
    # corrupt lines instead of one good one - and the same hazard exists at the tail
    # from a torn concurrent append.
    $fragmentBytes = Get-TrailingFragmentLength $chunk
    $keepBytes = $chunk.Length - $fragmentBytes
    if ($keepBytes -le 0) {
        return (Send-OversizeLine $Path $Offset $Rotated $ExpectedHead $fileBytes)
    }
    if ($fragmentBytes -gt 0) {
        $trimmed = New-Object byte[] $keepBytes
        [Array]::Copy($chunk, 0, $trimmed, 0, $keepBytes)
        $chunk = $trimmed
    }

    # Rotation DURING the read (the TOCTOU). The dispatcher can rename the file
    # between our size read and this one, in which case the bytes above came from
    # the NEW file: shipping them labelled offset=<old> loses the old file's real
    # tail and then persists an offset over the top of it. The window is
    # milliseconds and rotation is once per generation, but the corruption is silent
    # and permanent.
    if ((Get-FirstLineFingerprint $Path) -ne $ExpectedHead) {
        Write-ShipDebug "head changed under us -> discarding chunk at $Offset"
        return $false
    }
    if (-not (Send-ChunkRequest $chunk $Offset $chunk.Length $Rotated)) { return $false }
    $script:advanceBytes = $chunk.Length
    return $true
}

# A single line longer than one request. "If the chunk has no newline, ship it
# whole" was incoherent: the chunk was ALREADY truncated to the cap, so "whole"
# shipped a PARTIAL line, contradicting the invariant the server parser depends on.
# Both branches here are unreachable in a healthy install (`raw=` is capped at 400
# chars), so a multi-megabyte line means something already went wrong - which is why
# the over-ceiling case SKIPS FORWARD instead of retrying: a corrupt line must not
# park the file forever.
function Send-OversizeLine {
    param([string]$Path, [int64]$Offset, [int]$Rotated, [string]$ExpectedHead, [int64]$FileBytes)
    Find-LineEnd $Path $Offset
    if ($script:lineLength -gt 0) {
        if ($script:lineLength -le $script:maxLineBytes) {
            $line = Read-Range $Path $Offset ([int]$script:lineLength)
            if ($null -eq $line -or $line.Length -eq 0) { return $false }
            if ((Get-FirstLineFingerprint $Path) -ne $ExpectedHead) { return $false }
            if (-not (Send-ChunkRequest $line $Offset $line.Length $Rotated)) { return $false }
            $script:advanceBytes = $line.Length
            return $true
        }
        # Over the ceiling: skip PAST ITS NEWLINE, never by a fixed amount, so the
        # new offset lands exactly on the start of the next line.
        Write-ShipLog "outcome=skip reason=oversize-line file=$($script:targetBaseName) offset=$Offset bytes=$($script:lineLength)"
        $script:advanceBytes = $script:lineLength
        return $true
    }
    if ($script:lineSearchHitEof -eq 1) {
        $remainingBytes = $FileBytes - $Offset
        if ($remainingBytes -le 0) { return $false }
        # A ROTATED generation is frozen, so its unterminated final line is complete
        # and will never grow: send it rather than stalling on .1 forever, which
        # would also stop the live log from ever resetting.
        if ($Rotated -eq 1) {
            # The ceiling applies to this tail too. It is a line like any other,
            # and the newline search that produced it may have spanned every scan
            # window - up to MAX_SCAN_WINDOWS * maxLineBytes, 256 MiB at the
            # defaults - so without this the branch can post a single body far
            # past the ~1 MiB (4 MiB for one oversized line) the receiver is
            # promised, after allocating it.
            if ($remainingBytes -gt $script:maxLineBytes) {
                Write-ShipLog "outcome=skip reason=oversize-line file=$($script:targetBaseName) offset=$Offset bytes=$remainingBytes"
                $script:advanceBytes = $remainingBytes
                return $true
            }
            $tail = Read-Range $Path $Offset ([int]$remainingBytes)
            if ($null -eq $tail -or $tail.Length -eq 0) { return $false }
            if (-not (Send-ChunkRequest $tail $Offset $tail.Length $Rotated)) { return $false }
            $script:advanceBytes = $tail.Length
            return $true
        }
        # A LIVE file's unterminated tail is a line still being written. Wait for its
        # newline instead of shipping half of it.
        return $false
    }
    # The scan bound was exhausted without finding a newline: a single "line" larger
    # than MAX_SCAN_WINDOWS * maxLineBytes (256 MiB at the defaults). DO NOT ADVANCE.
    # An earlier version advanced by one window here, which is the same mid-line
    # landing Find-LineEnd exists to prevent: every later read becomes a fragment.
    # Stalling loses this file's diagnostics until someone looks at it; advancing
    # corrupts the dataset. It is logged every run so a stalled file is visible
    # rather than silent.
    Write-ShipLog "outcome=stall reason=unbounded-line file=$($script:targetBaseName) offset=$Offset scanned=$($script:maxLineBytes * $MAX_SCAN_WINDOWS)"
    return $false
}

function Send-ChunkRequest {
    param([byte[]]$Bytes, [int64]$Offset, [int]$Count, [int]$Rotated)
    $rotatedFlag = $false
    if ($Rotated -eq 1) { $rotatedFlag = $true }
    $body = @{
        host           = [string]$script:hostName
        actor_email    = [string]$script:actorEmail
        actor_name     = [string]$script:actorName
        shipper        = [string]$ShipperSlug
        shipper_version = [string]$ShipperVersion
        log_file       = [string]$script:targetBaseName
        offset         = $Offset
        bytes          = $Count
        rotated        = $rotatedFlag
        content_b64    = [Convert]::ToBase64String($Bytes)
    }
    if ($script:targetFamily) { $body['agent_family'] = [string]$script:targetFamily }
    $json = $body | ConvertTo-Json -Compress
    Write-ShipDebug "POST $($script:shipUrl) file=$($script:targetBaseName) offset=$Offset bytes=$Count rotated=$rotatedFlag"
    $httpCode = 0
    try {
        $payload = [System.Text.Encoding]::UTF8.GetBytes($json)
        $response = Invoke-WebRequest -Uri $script:shipUrl -Method Post `
            -Headers @{ 'x-rogue-api-key' = $script:apiKey } `
            -ContentType 'application/json' -Body $payload `
            -UseBasicParsing -TimeoutSec $HTTP_TIMEOUT -ErrorAction Stop
        $httpCode = [int]$response.StatusCode
    } catch {
        try { if ($_.Exception.Response) { $httpCode = [int]$_.Exception.Response.StatusCode } } catch { $httpCode = 0 }
    }
    # The offset advances ONLY on 2xx. A non-2xx, a transport failure or a timeout
    # leaves the state untouched, so the same range is re-sent next run: nothing is
    # ever marked exported on unconfirmed data. This makes 2xx load-bearing - it must
    # mean DURABLY ACCEPTED on the server, not merely received.
    if ($httpCode -ge 200 -and $httpCode -lt 300) { return $true }
    # THREE DIGITS, because curl prints `000` for a transport failure or a timeout and
    # both status documents tell the operator to look for `http=000`. Left as $httpCode
    # this logged `http=0` on Windows only, so the one string support greps for existed
    # on one platform. A real status is unaffected (401 formats as 401).
    Write-ShipLog ("outcome=fail file=$($script:targetBaseName) offset=$Offset bytes=$Count http=" + $httpCode.ToString('000'))
    return $false
}

# ── stage 9: one log file ──────────────────────────────────────────────────
function Invoke-DrainFile {
    param([string]$Path, [int64]$FileBytes, [int]$Rotated, [string]$ExpectedHead,
          [string]$PersistHead, [int64]$PersistSize, [string]$NormalizedPath)
    $iteration = 0
    while ($script:offset -lt $FileBytes) {
        if ($script:runBytesSent -ge $script:maxRunBytes) { Write-ShipDebug 'run budget spent'; return $false }
        $iteration++
        if ($iteration -gt $MAX_CHUNKS_PER_DRAIN) { Write-ShipDebug 'iteration guard'; return $false }
        if (-not (Send-NextChunk $Path $script:offset $Rotated $ExpectedHead)) { return $false }
        if ($script:advanceBytes -le 0) { return $false }
        $script:offset += $script:advanceBytes
        $script:runBytesSent += $script:advanceBytes
        Write-ShipState $script:stateKey $script:offset $PersistHead $PersistSize $NormalizedPath
    }
    return $true
}

function Ship-LogFile {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { Write-ShipDebug "no such log: $Path"; return }
    $script:targetBaseName = Split-Path $Path -Leaf
    $script:targetFamily = Get-FamilyForFile $script:targetBaseName
    $script:stateKey = Get-StateKeyForPath $Path
    if (-not $script:stateKey) { return }
    if (Test-WithinThrottleWindow $script:stateKey) { Write-ShipDebug "throttled: $($script:stateKey)"; return }
    if (-not (Lock-StateKey $script:stateKey)) { Write-ShipDebug "locked: $($script:stateKey)"; return }
    try {
        # Stamped the instant the lock is taken, BEFORE any upload - that is what
        # makes it a crash-loop guard rather than a bandwidth measure.
        Set-RunTimeStamp $script:stateKey

        $normalizedPath = Get-NormalizedPath $Path
        Read-ShipState $script:stateKey $normalizedPath
        $fileBytes = Get-FileLength $Path
        $currentHead = Get-FirstLineFingerprint $Path
        $script:runBytesSent = 0

        $rotated = $false
        if ($fileBytes -lt $script:offset) { $rotated = $true }
        if ($currentHead -and $script:stateHead -and $currentHead -ne $script:stateHead) { $rotated = $true }

        if ($rotated) {
            Write-ShipDebug "rotation detected for $($script:targetBaseName) (size=$fileBytes off=$($script:offset))"
            $rotatedPath = "$Path.1"
            if ((Test-Path -LiteralPath $rotatedPath) -and $script:stateHead) {
                $rotatedHead = Get-FirstLineFingerprint $rotatedPath
                $rotatedBytes = Get-FileLength $rotatedPath
                # Validating .1's head against the STORED head is what stops a double
                # rotation from re-shipping a generation we already sent. The size
                # floor is an independent second condition: a first-line window is not
                # a digest, so two generations whose first lines are byte-identical
                # would compare equal, and a different generation almost certainly has
                # a different size.
                if ($rotatedHead -eq $script:stateHead -and $rotatedBytes -ge $script:stateSize) {
                    # .1 is a WHOLE generation (up to ROGUE_LOG_MAX_BYTES), so it needs
                    # the same bounded chunk loop as the live file.
                    #
                    # A false return means either a failed upload or a spent run
                    # budget, and BOTH must return WITHOUT resetting the offset:
                    # resetting mid-.1 would throw away the rest of a rotated
                    # generation, which is silent loss. The next run re-detects the
                    # rotation and resumes .1 at the stored offset.
                    if (-not (Invoke-DrainFile $rotatedPath $rotatedBytes 1 $rotatedHead `
                                $script:stateHead $script:stateSize $normalizedPath)) { return }
                } else {
                    Write-ShipDebug '.1 does not match the stored head -> skipping it'
                }
            }
            $script:offset = 0
            Write-ShipState $script:stateKey 0 $currentHead $fileBytes $normalizedPath
        }

        [void](Invoke-DrainFile $Path $fileBytes 0 $currentHead $currentHead $fileBytes $normalizedPath)
    } finally {
        # try/finally, so an early return still releases the lock.
        Unlock-StateKey
    }
}

# ── main ───────────────────────────────────────────────────────────────────
function Invoke-Main {
    if (Test-ShouldStandDown) { exit 0 }
    try {
        [Net.ServicePointManager]::SecurityProtocol = `
            [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
    } catch {}

    Initialize-Args
    Import-ShipEnv
    Resolve-Knobs
    if (-not $script:apiKey) { Write-ShipDebug 'not configured -> no-op'; exit 0 }
    if (-not (Resolve-ShipActor)) {
        # Do NOT invent an identity. A wrong one creates an orphaned log_source row,
        # which is strictly worse than not shipping: the logs are uploaded, billed
        # and stored, and joined to nothing.
        Write-ShipLog 'outcome=skip reason=no-actor'
        exit 0
    }

    $script:stateDir = Join-Path (Join-Path (Get-UserHome) '.rogue') 'ship'
    if (-not (Test-Path -LiteralPath $script:stateDir)) {
        New-Item -ItemType Directory -Path $script:stateDir -Force | Out-Null
    }
    if (-not (Test-Path -LiteralPath $script:stateDir)) { Write-ShipDebug 'cannot create the state dir'; exit 0 }

    foreach ($target in (Get-TargetLogFiles)) {
        if (-not $target) { continue }
        Ship-LogFile $target
    }
    exit 0
}

# The ROGUE_PS_LIB_ONLY seam: load the helpers WITHOUT running the shipper, so
# tests/test_ship_logs.ps1 can dot-source and exercise them on Linux (where the
# main body stands down). Every pure helper is defined ABOVE this line.
if ($env:ROGUE_PS_LIB_ONLY) { return }

Invoke-Main
