#!/bin/sh
# Rogue presence-beacon throttle — SHARED, sourced by every sh-side heartbeat.
#
#   . "$PLUGIN_ROOT/scripts/beacon.sh"
#   if rogue_beacon_claim claude 1; then curl ... ; fi
#
# ONE COPY IS EDITABLE: scripts/shared/beacon.sh. Every plugin carries a
# byte-identical copy under plugins/<x>/scripts/, regenerated by
# scripts/sync-shared-scripts.sh and enforced by --check in CI. Editing a
# plugin's copy is silently reverted by the next sync. See that script for why
# copies exist at all (each plugin installs as a self-contained directory).
#
# WHY THIS IS SHARED RATHER THAN COPIED BY HAND. The presence beacon now fires on
# a per-TURN trigger as well as per-session (see "Two triggers, one script" in the
# root CLAUDE.md), so every plugin needs the same rate limit. The semantics below
# carry at least six traps that are individually easy to get wrong and impossible
# to notice in production - a padded zero, an oversized interval, a future stamp,
# a stamp written after the request instead of before, a per-family stamp path,
# and the numeric-zero-disables convention. Six hand-written copies of that in sh
# plus five in PowerShell would drift, and every drift is silent: the failure mode
# is either "no beacon ever again" (a roster row indistinguishable from an
# uninstalled plugin) or "a beacon on every single turn" (a fleet-wide request
# storm). One implementation, one test suite, per-plugin differences as arguments.
#
# Gemini is deliberately absent from the copies: it ships a single Node
# implementation, the same rule as ship-logs.mjs.
#
# NOTHING RUNS AT SOURCE TIME. This file only defines functions, so sourcing it is
# safe from a dispatcher that has already resolved its own state, and it must stay
# that way - Cursor sources it from inside the synchronous hook.

# The interval, resolved fresh on every call rather than cached at source time:
# the sh heartbeats source their env files before sourcing this, so the value in
# the environment is already the correct precedence result (bundled -> MDM ->
# per-user -> process env). PowerShell cannot do that - it parses the env files
# into a hashtable and never exports them - which is why beacon.ps1 has an extra
# Initialize-RogueBeacon step and this file does not.
#
# A NUMERIC ZERO DISABLES the throttle; a non-numeric value falls back to the
# default. Same rule as ROGUE_LOG_MAX_BYTES and ROGUE_SHIP_MIN_INTERVAL, so there
# is one convention to remember across the whole plugin. Note what zero means on a
# per-turn trigger: a beacon every turn. That is the knob doing what it says, not a
# footgun to clamp away - the default is what protects the fleet.
rogue_beacon_interval() {
  _rbi="${ROGUE_HEARTBEAT_MIN_INTERVAL:-900}"
  case "$_rbi" in ''|*[!0-9]*) _rbi=900 ;; esac
  # All-digit is not the same as representable: dash answers `-lt` on a value
  # wider than a signed 64-bit int with "Illegal number" on stderr and a FALSE,
  # which reads as "not throttled" and would loose a beacon on every turn. 18
  # digits is the widest that always fits; strip leading zeros first so a padded
  # zero is still judged on its value. Same clamp, same reason, as the log
  # rotation cap in every dispatcher.
  _rbi_t="$_rbi"
  while [ "${_rbi_t#0}" != "$_rbi_t" ]; do _rbi_t="${_rbi_t#0}"; done
  [ "${#_rbi_t}" -gt 18 ] && _rbi=900
  printf '%s' "$_rbi"
}

# Per-agent-family, under the ~/.rogue tree all six plugins share - so a machine
# running several coding agents throttles each family's beacon separately. The
# slug is an ARGUMENT for the same reason it is one in ship-logs.sh: nothing in
# here may derive a plugin's identity, and the families do not match the slugs
# anyway (codex ships under family `openai`).
rogue_beacon_stamp_path() {
  printf '%s' "$HOME/.rogue/beacon/.last-$1"
}

# Stamped BEFORE the request by every caller, which is what makes this a
# crash-loop guard as much as a rate limit: a beacon that hangs or dies still
# costs the next turn its attempt rather than retrying on every single one.
# 0700/0600 to match the log tree - this file says when a machine was active, and
# nothing else on the box needs to read that.
rogue_beacon_stamp() {
  ( umask 077
    _rbs="$(rogue_beacon_stamp_path "$1")"
    mkdir -p "${_rbs%/*}" 2>/dev/null
    date -u +%s > "$_rbs" 2>/dev/null ) || true
  return 0
}

# rogue_beacon_claim <slug> <unthrottled>
#
# Returns 0 when this beacon should be sent (and stamps), 1 when it should be
# skipped. Deciding and stamping are ONE call on purpose: a caller that forgot the
# stamp would leave the window permanently open and the throttle would silently do
# nothing.
#
# <unthrottled> is 1 for a session-start trigger and 0 for a per-turn one. Which
# event names those are is the CALLER's business - the six plugins spell them
# SessionStart, sessionStart, AfterAgent, agentStop, stop and (Antigravity, which
# has no session event at all) the first PreInvocation of a turn. Passing a
# boolean instead of an event name keeps this file free of six vocabularies.
#
# A session-start trigger is NEVER throttled: it fires once per session, and a new
# session is exactly when the roster wants the update (a re-install with a new
# version, the same user on a different surface).
rogue_beacon_claim() {
  _rbc_slug="$1"
  _rbc_unthrottled="${2:-0}"

  case "$_rbc_unthrottled" in
    ''|0|00) ;;
    *) rogue_beacon_stamp "$_rbc_slug"; return 0 ;;
  esac

  _rbc_int="$(rogue_beacon_interval)"
  if [ "$_rbc_int" -gt 0 ]; then
    _rbc_stamp="$(rogue_beacon_stamp_path "$_rbc_slug")"
    # Every unreadable, corrupt, empty or FUTURE stamp answers "not throttled". A
    # stamp we cannot trust must never be able to silence presence reporting - on
    # the roster that is indistinguishable from an uninstalled plugin. A stamp in
    # the future (clock stepped back, or a bad write) is stale, not a reason to
    # stay quiet until the clock catches up.
    if [ -r "$_rbc_stamp" ]; then
      _rbc_last="$(head -n1 "$_rbc_stamp" 2>/dev/null | tr -d '[:space:]')"
      _rbc_now="$(date -u +%s 2>/dev/null)"
      case "${_rbc_last:-}" in ''|*[!0-9]*) _rbc_last="" ;; esac
      case "${_rbc_now:-}" in ''|*[!0-9]*) _rbc_now="" ;; esac
      # Both sides clamped for the same reason as the interval: an 80-digit stamp
      # would make `-lt` fail with "Illegal number" instead of comparing.
      [ "${#_rbc_last}" -gt 18 ] && _rbc_last=""
      if [ -n "$_rbc_last" ] && [ -n "$_rbc_now" ] && [ "$_rbc_last" -le "$_rbc_now" ]; then
        if [ $((_rbc_now - _rbc_last)) -lt "$_rbc_int" ]; then
          return 1
        fi
      fi
    fi
  fi

  rogue_beacon_stamp "$_rbc_slug"
  return 0
}
